### ISSUE TITLE
support for vertically aligning values in a `let` (align-cljlet)

### ISSUE THREAD

**Issue by uvtc** [clojure-emacs/clojure-mode#126]
Would be nice if Emacs could help me turn this:

``` clojure
(let [thing "stuff"
      other-thing "other stuff"]
  ...)
```

into

``` clojure
(let [thing       "stuff"
      other-thing "other stuff"]
  ...)
```

This came up at https://github.com/bbatsov/clojure-style-guide/issues/10 , and samaaron mentioned there's already a mode that does this: https://github.com/gstamp/align-cljlet .

Is align-cljlet something that could be integrated into clojure-mode?

**Comment by dijonkitchen** [comment]
For posterity, this exists now: https://github.com/clojure-emacs/clojure-mode#vertical-alignment
