### ISSUE TITLE
Identation issues in docstrings

### ISSUE THREAD

**Issue by expez** [clojure-emacs/clojure-mode#241]
```clojure
(ns test.core
  "If I write a really long line without worrying about indentation
  and then call clojure-fill-paragraph to indent once I'm done it
  looks like this and all is well.

This paragraph on the other hand was created by hitting RET to indent
  manually.  Every time I do this the indentation moves all the way to
  the left, instead of staying aligned.  Calling clojure-fill-paragraph
  now will indent all but the first line in this paragraph properly.")
```

**Comment by tsdh** [comment]
@bzg The problem I have with the current `clojure-indent-line` function is that I frequently have example code and ASCII art in docstrings which shall not be touched.  E.g., I have

```` clojure
(defn foo
  "foo should be called like

     (with-bar something
       (foo x))

  where something is something."
  [x]
  (do-stuff-with m))
````

and after indentation I end up with

```` clojure
(defn foo
  "foo should be called like

  (with-bar something
  (foo x))

  where something is something."
  [x]
  (do-stuff-with m))
````

Of course, now you'll say "then don't hit TAB in docstrings" but I use [aggressive-indent-mode](https://github.com/Bruce-Connor/aggressive-indent-mode) which re-indents while typing.

Right now, I simply `fset` `clojure-indent-line` to `lisp-indent-line` which returns `'noindent` for strings.  That solves my issue but I don't think that forcing every line in a docstring to start with the same number of spaces is a good feature in general.  Maybe adding the clojure fill prefix in case there are less spaces would be ok, but removing spaces a user has intentionally added is not IMHO.

**Comment by bzg** [comment]
Hi Tassilo,

I don't have enough time at hand right now -- if you can come up with a patch for this, I'll gladly accept it!

Thanks in advance.

**Comment by stig** [comment]
I'm having indentation issues on things like this: https://github.com/Datomic/day-of-datomic/blob/master/src/datomic/samples/schema.clj#L50

**Comment by sandhu** [comment]
The #289 PR that got merged this weekend should address this issue.

**Comment by tsdh** [comment]
Great, thanks!

**Comment by stig** [comment]
Hurrah!

**Comment by raxod502** [comment]
But it still looks like `electric-indent-mode` is broken? I.e. if I press `RET` in a Clojure docstring, then point is at column 0 until I press `TAB` at which point it moves to column 2.

**Comment by bzg** [comment]
The behavior I see in a docstring with `clojure-mode version 5.7.0-snapshot` is this one:

- `RET` goes at the beginning of the next line, independantly of `electric-indent-mode` 
- `C-j` indents correctly with `electric-indent-mode` turned _off_, but do the same than `RET` otherwise

The docstring of `C-j` (aka `electric-newline-and-maybe-indent`) says:

> Insert a newline.
> If ‘electric-indent-mode’ is enabled, that’s that, but if it
> is *disabled* then additionally indent according to major mode.

So I'm inclined to think `RET` and `C-j` are behaving correctly here, although I too think this is all a bit confusing.  I've no good idea right on how to fix this right now.

Also beware that `clojure-mode` don't recognize docstring after the function's parameters:

```
(defn a-function
  "A well-placed docstring."
  []
  nil)

(defn another-function
  []
  "A misplaced docstring."
  nil)
```

**Comment by raxod502** [comment]
But the docstring for command `newline` (bound to `RET`) says this:

```
If ‘electric-indent-mode’ is enabled, this indents the final new line
that it adds, and reindents the preceding line.  To just insert
a newline, use M-x electric-indent-just-newline.
```

So your first bullet point sounds like wrong behavior of `clojure-mode` to me, since if `electric-indent-mode` is enabled then `RET` should indent the new line .

**Comment by bzg** [comment]
@raxod502 yes, you're right.

https://github.com/clojure-emacs/clojure-mode/pull/447 is an attempt at fixing the issue at point, please see the PR comment and let me know if this works for you as it works for me.

Thanks!
