### ISSUE TITLE
Create indentation tests

### ISSUE THREAD

**Issue by bbatsov** [clojure-emacs/clojure-mode#271]
Such tests would be really useful and will make the code less vulnerable to regressions. 

We can borrow ideas from [elixir-mode](https://github.com/elixir-lang/emacs-elixir/blob/master/test/elixir-mode-indentation-test.el) and [swift-mode](https://github.com/chrisbarrett/swift-mode/blob/master/test/indentation-tests.el).

**Comment by andrewhr** [comment]
@bbatsov looks interesting. One idea though: since indentation is _idempotent_, the test macro could receive only the expected version. That way the tests could read a bit more like documentation. Something like:

```elisp
(def-indentation-test vertically-aligns-function-args-spanning-multiple-lines 
  "
(filter even?
        (range 1 10))
")
```

Yep, I stealed the example from your style guide :wink:

**Comment by the-kenny** [comment]
You could even read the forms from an external file - no need to embed code in strings which always seems messy.
