### ISSUE TITLE
(defn$ ...) should provide similar syntax highlighting as (defn ...) 

### ISSUE THREAD

**Issue by dubiousdavid** [clojure-emacs/clojure-mode#273]
Is there some reason why (defn$ my-fn ...) doesn't syntax highlight the same as (defna my-fn ...)?  Or is there some special way to enable function-like syntax highlighting for this special macro in my code?

Emacs 24.3
OS X Yosemite
clojure-mode 3.1.0-snapshot

**Comment by bbatsov** [comment]
The regexp that does the highlighting requires only letters and hyphens. We can always adjust it, but I'm not sure we should, as it has served us well for years. Adding symbols like `$` to a def form looks pretty strange to me.
