### ISSUE TITLE
`..` and `doto` indent differently

### ISSUE THREAD

**Issue by tanzoniteblack** [clojure-emacs/clojure-mode#275]
Minor indentation issue: Using clojure-mode version 4.0.1 `doto` and `..` macros indent different, which seems unexpected to me:

```clojure
(doto (ClientConfiguration.)
  (.withProtocol proto)
  (.withMaxErrorRetry 0))
```
vs
```clojure
(.. (ClientConfiguration.)
    (withProtocol proto)
    (withMaxErrorRetry 0))
```

**Comment by bbatsov** [comment]
This is intentional. `..` has the same semantics as `->` and therefore should have the same indentation. You can customize this (as noted in the README) if you dislike the default settings.
