### ISSUE TITLE
Odd indentation of with-open vs. with-redefs

### ISSUE THREAD

**Issue by weavejester** [clojure-emacs/clojure-mode#276]
I'm wondering what's the canonical way of indenting a form like:

```clojure
(with-open
[x y]
x)
```

In clojure-mode, this is indented thus:

```clojure
(with-open
    [x y]
  x)
```

Is the double-indentation of the `[x y]` form deliberate, or an error? The `with-redefs` form indents differently:

```clojure
(with-redefs
  [x y]
  x)
```

This seems more logical to me, but I'd like to get your opinion. I'm working on [cljfmt](https://github.com/weavejester/cljfmt) and would like them to have the same indentation scheme if at all possible.

For reference, cljfmt currently indents both forms as:

```clojure
(with-open
 [x y]
  x)
```

Because it doesn't register `[x y]` being part of the block, so defaults to normal list indentation. However, I'm leaning toward changing this to indent 2 spaces.

**Comment by weavejester** [comment]
These are the indentation structures I think I'd be temped to go by:

```clojure
(with-open [x y] z x)

(with-open [x y] z
                 x)
 
(with-open [x y]
  z
  x)

(with-open
  [x y]
  z
  x)
```

In other words, if newlines only occur after a certain point, the list indents normally, but if newlines occur before a certain point, the indentation is fixed.

Thoughts?

**Comment by bbatsov** [comment]
Btw, I've always intended those forms to be used like this:

```
(with-open [x y] 
  z x)
```

Same applies for all forms that accept a `bindings` vector.

**Comment by bbatsov** [comment]
To expand on my previous comment - certainly the two forms should be indented in the same manner, but I definitely don't think that what `cljfmt` is doing right now is idiomatic at all (maybe this could be configurable?). Outside of `defn` and relatives I've rarely seen anyone place the binding vector on a line of its own.

**Comment by bbatsov** [comment]
P.S. I cannot reproduce your problem with `clojure-mode` installed from MELPA. Both forms are indented identically (and there's no different handling for them in the code). Perhaps you're using some old version of `clojure-mode`?

**Comment by weavejester** [comment]
Ah, looks like this was fixed within the past month or so. My apologies.

While most users don't place their newlines in odd places, it would be nice if there was a consistent strategy when they do. I'd like to get your opinion on what that strategy is.

For example, the `do` block is indented in two ways, depending on whether there's a new line before it's first argument:

```clojure
(do x
    y)

(do
  x
  y)
```

In clojure-mode the `are` block is still indented strangely:

```clojure
(are [x y]
    (= x y)
  1 1)
```

While cljfmt tries to line things up:

```clojure
(are [x y]
     (= x y)
  1 1)
```

In cljfmt's case it uses normal list indentation until after the second argument, at which point it switches to a fixed indentation.

**Comment by bbatsov** [comment]
> For example, the do block is indented in two ways, depending on whether there's a new line before it's first argument:
> 
> (do x
>     y)
> 
> (do
>   x
>   y)

I strongly believe that the first indentation has no merits whatsoever. In CL/EL it's pretty odd to see `progn` used in this manner as well. 

 > In clojure-mode the are block is still indented strangely:
> 
> (are [x y]
>     (= x y)
>   1 1)

`clojure-mode` can't know the ns in which a symbol would resolve, so it doesn't handle specially `are` at all. It used to do so before version 3.0, but this was resulting in false positives as it's perfectly sensible to have `are` defined in a namespace other than `clojure.test`.

Semantic indentation requires a running repl (or some form static code analysis). Perhaps one day will have semantic indentation provided by CIDER.

**Comment by weavejester** [comment]
> I strongly believe that the first indentation has no merits whatsoever. In CL/EL it's pretty odd to see `progn` used in this manner as well.

It has the merit of saving a line of code without (IMHO) loss of clarity, which is really all you can hope for in an indentation scheme. It's also a fairly common form of indentation; I'm not sure whether it's the dominant form or not, but it certainly isn't rare.

> `clojure-mode` can't know the ns in which a symbol would resolve, so it doesn't handle specially are at all.

Ah, my mistake. It was picking up an override from another .el file. However, `deftype` is defined in `clojure-mode.el`, and has the same behaviour:

```clojure
(deftype Foo
    [x]
  Object
  (toString [_] x))
```

Is the double indent an error?

**Comment by bbatsov** [comment]
Looking at the `clojure-mode` code it seem we expect `deftype` to be indented like this:

```
(deftype Foo [x]
  Object
  (toString [_] x))
```

Not sure what the original reasoning was, as your suggestion seems sensible.

P.S. It also makes sense to document acceptable indentation schemes in the Clojure style guide. I think the guide and `cljfmt` should be kept in sync (like Ruby's style guide and `RuboCop`).

**Comment by weavejester** [comment]
I think so too, but I wonder what to do when users have added line breaks in a way counter to general practice. e.g. how do we deal with something like:

```clojure
(if a b
    c)
```

Do we just say that this behaviour is undefined? Or should we standardise even on this?

**Comment by bbatsov** [comment]
My preference would be to standardise this. There can be some option how to treat cases like the `if` example - either to always convert them to a proper multi-line form or to collapse them on a single line when this won't exceed some line length limit. I use similar techniques in RuboCop and the Ruby hackers are generally happy that they have customisation options.

Handling more complex examples might be more involved, though. There can also be an option to ignore ambiguous code in case someone is super fond of their crazy style. :-)

**Comment by yatesco** [comment]
My 2 cents - if I am running a tool with the intent of that tool
intelligently formatting my code then I would want it to have an opinion on
pretty much everything with the option of tweaking its opinion.

I think the type of person who would write code like that either:
 - is a bit slap/dash, doesn't particularly care about coding conventions
and expects it go away when it is formatted
 - has made a positive decision that that is the right thing and wouldn't
ever run 'auto-format'

**Comment by weavejester** [comment]
>  There can be some option how to treat cases like the `if` example - either to always convert them to a proper multi-line form or to collapse them on a single line when this won't exceed some line length limit.

Sure, and that's an option the user could enable. But if the user has enabled automatic formatting of indentation *only*, if the tool is forbidden from changing how the lines break, how should we be indenting those forms by default?

**Comment by bbatsov** [comment]
> Sure, and that's an option the user could enable. But if the user has enabled automatic formatting of indentation only, if the tool is forbidden from changing how the lines break, how should we be indenting those forms by default?

It might depend on the situation at hand - if the indentation is "somewhat" reasonable it can further indented, otherwise it should probably be completely ignored (left as is). The `if` example you gave would go to the second category.

Btw, I think it makes a lot of sense for `cljfmt` to add a mode that simply reports indentation problems instead of fixing them. I know that now you can compare the diffs, but this is not something that can be easily integrated into editors.

**Comment by weavejester** [comment]
For cljfmt at least, it's important that it always has an opinion for indentation. Maybe I'll draft up some general rules. I'll close this issue, as we've drifted off topic :)

If you have some ideas on how to report indentation problems for editors, let me know.
