### ISSUE TITLE
Apply font-lock-comment-face to (comment...) and #_... expressions

### ISSUE THREAD

**Issue by nahuel** [clojure-emacs/clojure-mode#277]
Maybe this feature was added by merging #83 but then it was removed?

**Comment by bbatsov** [comment]
Yes, it was more trouble than it was worth. There might be some merits to treating `#_` as a comment, but it definitely doesn't make much sense about `comment`.

**Comment by expez** [comment]
@bbatsov can we cherry-pick the font-lock functionality for `#_` back into master or was it broken?

**Comment by bbatsov** [comment]
@expez Seems you were part of the discussion that killed this feature https://github.com/clojure-emacs/clojure-mode/issues/215 :-)

**Comment by expez** [comment]
Damn, that's almost a year ago.  Time flies!  

I still think highlighting stuff that is commented out with `#_` is a good idea: reader macros are ubiquitous so it would be nice to get some hinting that an expression isn't being considered by the reader.

**Comment by bbatsov** [comment]
I don't disagree, but I don't have time to work on this and would not restore the old crappy implementation. Patches welcome! :-)

**Comment by bbatsov** [comment]
@Malabarba Ideas about this would be welcome as well. It has been in limbo for ages and I don't see myself revisiting it any time soon, but you've been on a roll lately with the clojure-mode fixes. :-)

**Comment by Malabarba** [comment]
No attractive ideas at least. The solution I wrote for font-locking
locals/ns-forms in cider should apply here more-or-less. But frankly, that
was such a pain to write I have to assume there is a better way.

2015-11-09 20:33 GMT+00:00 Bozhidar Batsov <notifications@github.com>:

**Comment by alexander-yakushev** [comment]
Probably hijacking an issue here, but it might be better to extend this to reader conditionals as well, the way Common Lisp and SLIME do it.

In Lisp you can have `#+ccl (+ 2 2) #+sbcl (+ 4 4)` and one of them will be dimmed depending on what implementation you are currently in. Hence, dimming `#+nil` is just a single case of the more general mechanism. Now that we have reader conditionals, it is slightly relevant for us as well.

**Comment by Peeja** [comment]
@alexander-yakushev What does it mean to be "in" an implementation? To have that language's REPL active?

**Comment by alexander-yakushev** [comment]
Yes. For Lisp SLIME handles it, which means the dimming of inactive feature expressions only works when connected to SWANK (except for `#+nil` which I guess is hardcoded into lisp-mode). For Clojure it will be equivalent of working only in active connected cider-mode.

**Comment by Malabarba** [comment]
Yes, this connection-sensitive feature (if it were to be implemented) would have to go in cider, which already has some dynamic font-locking. But the `#_` comments can be handled by clojure-mode. 

The relevant slime code for us to copy seems to be this (thanks to Alex for the link) : https://github.com/slime/slime/blob/master/contrib/slime-fontifying-fu.el#L186

**Comment by bbatsov** [comment]
I'd file separate issues for those suggestions.

On Wednesday, 2 December 2015, Artur Malabarba <notifications@github.com>
wrote:

> Yes, this connection-sensitive feature (if it were to be implemented)
> would have to go in cider, which already has some dynamic font-locking. But
> the #_ comments can be handled by clojure-mode.
>
> The relevant slime code for us to copy seems to be this (thanks to Alex
> for the link) :
> https://github.com/slime/slime/blob/master/contrib/slime-fontifying-fu.el#L186
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/clojure-emacs/clojure-mode/issues/277#issuecomment-161465171>
> .
>


-- 
Best Regards,
Bozhidar Batsov

http://www.batsov.com

**Comment by alexander-yakushev** [comment]
@Malabarba Yay, awesome!

**Comment by Peeja** [comment]
@Malabarba :cake::exclamation:

**Comment by Malabarba** [comment]
TBH, this was a bit easier than I expected, so I suspect I might be missing something. Let me know if you notice anything odd in the behaviour.

**Comment by alexander-yakushev** [comment]
+1 reason why `#_` is better than `;;` — it doesn't disable Paredit, so I can still use structured editing insde the commented area. Also I don't have to worry that after uncommenting the structure will be broken.
