### ISSUE TITLE
`are` macro indentation

### ISSUE THREAD

**Issue by Malabarba** [clojure-emacs/clojure-mode#284]
`clojure-mode` indents the `are` macro like this:

    (are [x] (#'t/listy? x)
         '()
         `()
         '(a))

Whereas I believe it should be like this:

    (are [x] (#'t/listy? x)
      '()
      `()
      '(a))

Cheers,

**Comment by bbatsov** [comment]
Oh, I guess I misread the comment in the `cider-nrepl` ticket. I'll have this fixed.

**Comment by Malabarba** [comment]
No. I believe I miswrote the comment. :-)
