### ISSUE TITLE
font-lock broken in emacs earlier than 24.3

### ISSUE THREAD

**Issue by pyb** [clojure-emacs/clojure-mode#285]
Hi, Clojure Syntax Highlighting on my emacs 24.1.1 seems completely broken, I am getting a lot of these errors
Error during redisplay: (void-function function-get) 
Is this a known issue?

**Comment by bbatsov** [comment]
Haven't really tested anything on 24.1. :-) I might have used something that's not available there... If you can update to a newer Emacs I'd suggest doing so.

**Comment by pyb** [comment]
It looks like function-get is only in from emacs 24.3 from March 2013

**Comment by bbatsov** [comment]
Ah, yeah. I borrowed some code from a newer Emacs version to fix the font-locking of docstrings. This was a while back and you're the first person who notices this, which leads me to believe it might be better to simply bump the minimum supported Emacs version. Seems few people use 24.1 these days.
