### ISSUE TITLE
Reader conditional indentation

### ISSUE THREAD

**Issue by jenanwise** [clojure-emacs/clojure-mode#292]
Clojure 1.7 has the new `#?` reader conditionals.

Expected:

```clojure
#?(:clj :foo
   :cljs :bar)
```

Actual:
```clojure
#? (:clj :foo
         :cljs :bar)
```

**Comment by bbatsov** [comment]
Yeah, we don't support this yet.

**Comment by benfleis** [comment]
+1 - Would love to see this - working on datascript / cljc, and have to do lots of manual fixes. Would it be a major change? (I just had a first glance at the code, but unclear where to start with this...)

**Comment by bbatsov** [comment]
Probably we should find a way to recycle the logic for sets. We can treat `#?()` as a literal similar to a set literal or something like this.

**Comment by chadharrington** [comment]
+1 - This would be very helpful.

**Comment by bbatsov** [comment]
I'm not sure when I'd be able to work on this, so if someone wants to pick up the slack in the mean time I definitely won't mind. :-)
