### ISSUE TITLE
Indentation for lists and function calls

### ISSUE THREAD

**Issue by gdanov** [clojure-emacs/clojure-mode#293]
Hi,
 Browsed the issues and experimented reading the code but could not solve my compliant:

lists and function calls are not indented it the same way as calls to built-in functions.

    (xyz abc
         aoe)

How can I configure clojure-mode to use the same indentation for all my functions?

Did my best to eliminate influences from the extra packages I have (nothing exotic) so sorry if this is not a problem related to clojure-mode.

cheers

**Comment by bbatsov** [comment]
> How can I configure clojure-mode to use the same indentation for all my functions?

I don't understand what you're trying to do.

Perhaps you want to set `clojure-defun-style-default-indent` to `t`, but I can't be sure.

**Comment by gdanov** [comment]
thank you, this achieved the result I wanted. If I understand right enabling this option disables all custom settings in `define-clojure-indent`?

**Comment by bbatsov** [comment]
Yes.

**Comment by gdanov** [comment]
thanks
