### ISSUE TITLE
clojure-in-docstring-p

### ISSUE THREAD

**Issue by phillord** [clojure-emacs/clojure-mode#295]
There is an off-by-one error in clojure-in-docstring-p.

It happens when the first line is zero width!

Debugger entered--Lisp error: (args-out-of-range 0 0)
  get-text-property(0 face)
  clojure-in-docstring-p()
  (if (clojure-in-docstring-p) (save-excursion (beginning-of-line) (if (looking-at "^\\s-*") (progn (replace-match (clojure-docstring-fill-prefix))))) (lisp-indent-line))
  clojure-indent-line()
  indent-according-to-mode()
  electric-indent-post-self-insert-function()
  self-insert-command(1)
  newline(nil 1)
  call-interactively(newline nil nil)
  command-execute(newline)

**Comment by bbatsov** [comment]
> It happens when the first line is zero width!

Can you elaborate on that? A repro case would be helpful.

**Comment by phillord** [comment]
Sorry for the terse report! I had a four year old jump on my half-way through.

Reproducible case: Open an empty file in Clojure mode, hit tab. It breaks.

My diagnosis is:

    (get-text-property (1- (point-at-eol) 'face)


is illegal since with a empty first line `(1- (point-at-eol))` returns `0`.
