### ISSUE TITLE
Wrong indentation for cond forms when conditions contain multiple forms

### ISSUE THREAD

**Issue by turbopape** [clojure-emacs/clojure-mode#296]
Hi,

For cond forms, I expect the condition forms to be justified, which is not the case when I have conditions compound of multiple forms (as for 'and' or 'or'), they get indented one level plus the previous condition, like so:
(cond 
  (and () () ) (...)
      (and ()()) ...

**Comment by turbopape** [comment]
Github suppressed my indentation ... I ment :
(cond 
__(and (..)(..)) ()
____(and (...)(..)) (..)

**Comment by expez** [comment]
Can't reproduce.  Please provide a full code example which we can copy/paste into a clojure-mode buffer to see the problem.

Are you sure you are on the latest version of clojure-mode?  Can you reproduce the problem starting from `emacs -q`, that is without loading any of your own configuration?

**Comment by turbopape** [comment]
I am currently on the road,

Will do that as soon as I get access to my laptop

**Comment by MatthewDarling** [comment]
```clojure-mode-display-version``` says 4.1.0, ```emacs-version``` says 24.5.1.

Here's a code sample, indented as it was on my machine:

```clojure
(defn example-fn
  [data]
  (cond
    (and (contains? data :x)
         (contains? data :y)) :success
         (empty? data) :failure
         :else :undefined))
```

If the ```and``` is entirely on a single line, then it is indented correctly. This happens any time a form in ```cond``` is split across multiple lines.

**Comment by aiba** [comment]
Just hit this same bug.  Emacs 24.5.1, clojure-mode 4.2.0-snapshot.

**Comment by Malabarba** [comment]
This is an Emacs bug. The same happens on `emacs-lisp-mode` with the following sexp:

    (progn
      (and 1
           2) 3
           4)

I'll report it upstream, but there's not much clojure-mode can do for now.
