### ISSUE TITLE
Navigate statements, top-level forms

### ISSUE THREAD

**Issue by andreas-roehler** [clojure-emacs/clojure-mode#297]

**Comment by andreas-roehler** [comment]
Let's have some mode-specific navigation commands.

PR in consideration.

**Comment by expez** [comment]
This is solved by `imenu`, unless you had something else in mind?

**Comment by andreas-roehler** [comment]
See code-example below: how to jump between heads of list def, map, range?

(def x (map (fn [n]
              (struct-map desilu
                          :fred n
                          :ricky 2
                          :lucy 3
                          :ethel 4))
            (range 100000)))

**Comment by expez** [comment]
`smartparens`/`paredit`, `ace-jump` or plain old searching.

**Comment by andreas-roehler** [comment]
Let's assume cursor is at paren of "(def" - how to jump to "(map"?

**Comment by expez** [comment]
I'll usually call `sp-down-sexp` to get that job done.

Take a look at [smartparens](https://github.com/Fuco1/smartparens) it's pretty cool!

**Comment by andreas-roehler** [comment]
Yeah, that's great. Thanks! But wait before closing this: ":fred n" is an expression, right? When yes, how to travel. mark, copy expressions?

**Comment by expez** [comment]
I use `evil-mode` so I'd do `ya"` to copy the string and `va"` to mark it.  To travel past it I would use `sp-forward-sexp`.

**Comment by bbatsov** [comment]
This request seems outside the scope of `clojure-mode`. As @expez said there are a ton of generic tools for navigation & selection. I'd also add here `expand-region` and `easy-kill`.
