### ISSUE TITLE
Automatic insertion of namespace declaration does not work for boot projects

### ISSUE THREAD

**Issue by timothypratley** [clojure-emacs/clojure-mode#303]
Boot uses a build.boot file instead of project.clj

**Comment by bbatsov** [comment]
`clojure-mode` has no such feature. Perhaps you're using `clj-refactor.el`?

**Comment by timothypratley** [comment]
That is true, but clj-refactor.el  uses clojure-expected-ns from clojure-mode:
https://github.com/clojure-emacs/clj-refactor.el/issues/180#issuecomment-117468331

It is just a minor thing and can be worked around by touching an empty project.clj

Just raising it as boot is gaining popularity, and such behavior can confuse users

**Comment by bbatsov** [comment]
Ah, yes, now I understand what you mean. I'll have this fixed.
