### ISSUE TITLE
Indentation bug related to namespace metadata tags 

### ISSUE THREAD

**Issue by cheesinglee** [clojure-emacs/clojure-mode#304]
Adding a metadata tag to a namespace declaration causes the following lines in to be indented improperly (4 spaces instead of 2).

```clojure
(ns ^:metadata my.namespace
    (:use clojure.test))
...
```

However, if a docstring is present, then indentation is correct again.

```clojure
(ns ^:metadata my.namespace
  "my docstring"
  (:use clojure.test))
```

This issue was observed with emacs 24.5.1 and clojure-mode 4.2.0-snapshot, on Arch Linux x86_64.

**Comment by bbatsov** [comment]
Likely this has been broken since day 1. Guess we should try to fix it eventually.
