### ISSUE TITLE
Visual display of docstring

### ISSUE THREAD

**Issue by arichiardi** [clojure-emacs/clojure-mode#305]
First of all, I don't know if this is the right place, but I upgraded my ``clojure-mode``` package and saw a drastic change in the way the doc string is displayed.

![selection_017](https://cloud.githubusercontent.com/assets/1724788/8579292/023848c6-25b4-11e5-94ac-75f6d0972baf.png)

Is there a way to have a less visible face? Is this related to the refactoring of the extra font package (which I have not loaded I guess?

**Comment by bbatsov** [comment]
It's related only to your colour theme. Nothing related to docstrings has been changed in `clojure-mode` recently.

**Comment by arichiardi** [comment]
Great thanks and sorry for opening the issue in the wrong place.
