### ISSUE TITLE
Wrong let indentation

### ISSUE THREAD

**Issue by Malabarba** [clojure-emacs/clojure-mode#308]
This is how clojure-mode indents the following form.

    (let [{{{sha :sha} :head} :pull_request,
           {{user :login} :owner, :as repo} :repository} body
           base-analysis (something repo)]
      ...)

It's a pretty complicated destructuring, but the important point is that the indentation engine is indenting `base-analysis` as if it were part of the map above it, but it's really a whole new let-bind.

**Comment by bbatsov** [comment]
That's not an isolated case - pretty much every more complex scenario breaks the indentation as so much was originally copy/pasted or inherited from `lisp-mode`. Everything needs to be examined and re-engineered, but I don't see this happening any time soon.

**Comment by bbatsov** [comment]
See also #45 and https://github.com/clojure-emacs/clojure-mode/issues/270

**Comment by Malabarba** [comment]
It's not a huge deal anyway. :)

**Comment by bbatsov** [comment]
Yeah, I guess. Still, sooner and later we need to clean up the indentation mess. Like CIDER, `clojure-mode` was put together rather quickly and still carries quite the legacy around. But on the positive side, we're always making progress, albeit a bit slowly.

**Comment by Malabarba** [comment]
Yeah, I tried to write an `indent-line` function for ahk scripts a couple of years ago and I know how nasty they can be.
