### ISSUE TITLE
Wrong namespace when source path is src/cljc

### ISSUE THREAD

**Issue by yatesco** [clojure-emacs/clojure-mode#310]
Assume I have `src/cljc/a/b/c.cljc`. If I navigate in dired to `src/cljc/a/b` and then `C-x C-f new.cljc` then a new buffer is created `(ns cljc.a.b.new)`.

Namespaces are setup correctly so `src/cljc` is a source path according to project.clj.

Libraries are Clojure 1.7.0 and snapshot cider.

**Comment by bbatsov** [comment]
I haven't played with `cljc` yet. I'm assuming `src/cljc` is the standard layout and we should take this into account, right?

**Comment by expez** [comment]
This happens with `src/cljs` and `src/clj` too, doesn't it?

**Comment by yatesco** [comment]
Yep. Let me try `src\clj` and `test\clj` to see if it is specific to the clojure reader functionality.

**Comment by bbatsov** [comment]
I guess we need a list of folders which to drop from the generated `ns`. That should be pretty simple to do.

**Comment by yatesco** [comment]
Yep, it behaves the same with `src/clj` and `src/cljs`

**Comment by yatesco** [comment]
Thanks for the quick response guys.
