### ISSUE TITLE
Automatically created test namespace is wrong when nested source dir

### ISSUE THREAD

**Issue by yatesco** [clojure-emacs/clojure-mode#311]
Assume I have `src/cljc/a/b/c.cljc`. If I navigate in dired to test/cljc/a/b and then C-x C-f new_test.cljc then a new buffer is helpfully created `(ns cljc.a.b.new_test)` (filed in #310). However, it also requires:

```Clojure
(:require [cljc.a.b.new :refer :all]
            [clojure.test :refer :all])
```

(In terms of style I would suggest it is actually `[a.b.new :as sut]` for consistency, but that is a personal style issue).

Namespaces are setup correctly so `src/cljc` is a source path and `test/cljc` is a test path according to project.clj.

Libraries are Clojure 1.7.0 and snapshot cider.

**Comment by bbatsov** [comment]
Hmm, this definitely not in `clojure-mode`. @expez I'm assuming this is coming from `clj-refactor`, right?

P.S. I also dislike the usage of `:refer :all`.

**Comment by expez** [comment]
The broken function is `clojure-expected-ns` which is the cause of this: https://github.com/clojure-emacs/clojure-mode/issues/310#issuecomment-125926167

`clj-refactor` uses that same function to create the test namespace which prompted this issue to be created

**Comment by expez** [comment]
This can be closed too, was hoping github would understand multiple issues closed by same commit

**Comment by yatesco** [comment]
Thanks for the quick response guys.
