### ISSUE TITLE
Wrong indentation in letfn and defrecord protocol extending forms.

### ISSUE THREAD

**Issue by niwinz** [clojure-emacs/clojure-mode#315]
Hello!

In recent versions I found that `letfn` and `defrecord` are wrong indented. Examples:

```clojure
(letfn [(foooo-baaar [x y]
                     (+ x y)]
  (...))
```

```clojure
(defrecord A [b]
  Protocol
  (foo []
       (println "hello")))
```

I have done some research, and this start happens at this commit: https://github.com/clojure-emacs/clojure-mode/commit/0bf874e52bb32dce15f721e15c17a5f4758552ec

If I download and install just the previous commit (https://github.com/clojure-emacs/clojure-mode/commit/fa8dd01bfc82e8851a3ae687463fc988320528fc) everything just return to work as expected.

Context:
GNU Emacs 24.5.1
OS: Archlinux

Thanks for your work in this package!

**Comment by bbatsov** [comment]
Likely changing `last` broke this, as everything else stayed exactly the same. Guess I'll have to revisit this commit.

**Comment by bbatsov** [comment]
Hmm, doesn't seem to be this, I just tested this and remembered why I did it - because `last` returned the last cons cell, not the last element itself. So, this is an equivalent transformation.

**Comment by bbatsov** [comment]
@Malabarba @expez Does something seem problematic to you in the supposedly equivalent code I wrote?

**Comment by expez** [comment]
After looking over the code in 0bf874e and concluding it was a true refactoring, I tried to reproduce the issue in the OP and it works just fine on my computer.

**Comment by niwinz** [comment]
Can I provide additional info that will help you to reproduce the error?

**Comment by expez** [comment]
Can you reproduce the problem loading only clojure-mode, and none of your own config?  You can start emacs without loading your config by doing `emacs -q`.  You can then navigate to `.emacs.d/elpa/clojure-mode/clojure-mode.el` and manually load the file with `M-x eval-buffer <RET>` before opening a buffer in clojure-mode to check the indentation.

**Comment by niwinz** [comment]
Yes, I can reproduce the bug without loading my config.

If I load the clojure-mode.el from this commit: https://github.com/clojure-emacs/clojure-mode/commit/0bf874e52bb32dce15f721e15c17a5f4758552ec I can reproduce the wrong behavior. But If I load clojure-mode.el from previous commit (https://github.com/clojure-emacs/clojure-mode/commit/fa8dd01bfc82e8851a3ae687463fc988320528fc), it works as expected.

**Comment by Malabarba** [comment]
I haven't had a chance to try reproducing it, but the commit in question looks fine to me too. 

What do you get if you evaluate `(last '(1 2 3 4))`?

**Comment by niwinz** [comment]
Yes, this part works as expected:

```
(last '(1 2 3 4))
;; => (4)
```

I have done some additional research, applying each change manually, and I found that the problematic part is the change of `destructuring-bind` -> `cl-destructuring-bind`.

**Comment by expez** [comment]
`cl-destructuring-bind` is defined in `cl-macs.el`, yet the clojure-mode file only `require`s `cl-lib`.  Could that be the cause?

**Comment by Malabarba** [comment]
`cl-lib` takes care of loading `cl-macs`, but `cl-lib` is a complicated hack so something might be going wrong.

In particular, the `cl-lib.el` file ends like this:

    (unless (load "cl-loaddefs" 'noerror 'quiet)
      ;; When bootstrapping, cl-loaddefs hasn't been built yet!
      (require 'cl-macs)
      (require 'cl-seq))

Possibilities:

1. There's an old `cl-lib.el` in your load-path somewhere.
2. There's an old `cl-macs.el` in your load-path somewhere.
3. There's an old `cl-loaddefs.el` in your load-path somewhere.

So I guess I'm saying “Check your load-path”. :)

**Comment by niwinz** [comment]
I have created a new user in my sistem.
Started emacs with `emacs -q`
I have checked that only one possible version on the path of the cl-*.el files (in the filesystem and load-path emacs variable.
I have loaded the `clojure-mode.el` (that uses `cl-lib` instead of `cl`)
Loaded the a clojure file.

After doing that steps with completely clean environment I can perfectly reproduce the wrong indentation behavior. 

Additionally I have repeated that one in one machine that does not have installed emacs previously. So I have installed emacs (other version, concretelly "24.3.1") and I found the same wrong indentation in that new environment. 

Maybe I can create a docker image for create a isolated environment for reproduce it?

**Comment by expez** [comment]
Perhaps I have the odd machine out... @bbatsov @Malabarba  Are you guys seeing anything other than this:

![clojure-indent](https://cloud.githubusercontent.com/assets/1006557/9036520/94cdae50-39e2-11e5-856e-34e17bee20c7.PNG)

fwiw, the code in the OP is slightly off.  The body of foooo-baaar isn't closed properly.

**Comment by Malabarba** [comment]
> Perhaps I have the odd machine out... @bbatsov @Malabarba Are you guys seeing anything other than this:

Yes, I see the same as @expez . No problem here. I'm on 25.1, btw.

> Additionally I have repeated that steps in one machine that does not have installed emacs previously. So I have installed emacs (other version, concretelly "24.3.1") and I found the same wrong indentation in that new environment.

It's possible this was a bug in that macro which got fixed recently, but I ran git-blame on it and nothing caught my eye.

> Maybe I can create a docker image for create a isolated environment for reproduce it?

Sure, but it might be faster if you play around with `cl-destructuring-bind` yourself.

Does this produce the expected result?

    (cl-destructuring-bind (one . two) '(1 . 2)
      (message "ONE is %s and TWO is %s" one two))

What about this?

    (cl-destructuring-bind (def-beg . def-end) (bounds-of-thing-at-point 'sexp)
      (message "BEG is %s and END is %s" def-beg def-end))

**Comment by Malabarba** [comment]
@niwinz 


> Additionally I have repeated that steps in one machine that does not have installed emacs previously. So I have installed emacs (other version, concretelly "24.3.1") and I found the same wrong indentation in that new environment.

It's possible this was a bug in that macro which got fixed recently, but I ran git-blame on it and nothing caught my eye.

> Maybe I can create a docker image for create a isolated environment for reproduce it?

Sure, but it might be faster if you play around with `cl-destructuring-bind` yourself.

Does this produce the expected result?

    (cl-destructuring-bind (one . two) '(1 . 2)
      (message "ONE is %s and TWO is %s" one two))

What about this?

    (cl-destructuring-bind (def-beg . def-end) (bounds-of-thing-at-point 'sexp)
      (message "BEG is %s and END is %s" def-beg def-end))

**Comment by niwinz** [comment]
The first prints "ONE is 1 and TWO is 2" and the second prints "BEG is 211 and END is 341". But the second fails with "if: Wrong number of arguments: nil, 0" in emacs 24.

Also, I have done a isolated environment with docker that reproduces it: https://gist.github.com/niwinz/7b5621c7ed5251d93919

Just do this:
```bash
mkdir emacs-docker
cd emacs-docker
wget https://gist.githubusercontent.com/niwinz/7b5621c7ed5251d93919/raw/8744671ab9d89c64e038d0d30f0c22baa8f7e68e/Dockerfile
docker build --rm -t "emacs-docker:v1" .
docker run --rm -ti emacs-docker:v4 emacs -nw
```

Then, open the `clojure-mode.el` (located in the current directory), evaluate it, with `eval-buffer`, and then open the `test.clj` and try indent the letfn form and defrecord forms.

**Comment by bbatsov** [comment]
What's your Emacs version, btw?

**Comment by niwinz** [comment]
24.5.1 (It is reported in the first issue description also...)

**Comment by bbatsov** [comment]
Yeah, I asked and I saw this (that's why I deleted that comment). Sorry about this.

**Comment by cddr** [comment]
What would you expect to see with the second expression @Malabarba?
```
(cl-destructuring-bind (def-beg . def-end) (bounds-of-thing-at-point 'sexp)
  (message "BEG is %s and END is %s" def-beg def-end))
```

**Comment by Malabarba** [comment]
@cddr Yes, that's the expected outcome.

**Comment by Malabarba** [comment]
@niwinz The indentation engine has been severely changed since this issue was filed. In particular, it no longer has any calls to cl-destructuring-bind.

Do you still have the issue?

**Comment by j0ni** [comment]
I found this while searching for what I think is a relatively new issue for me. The `letfn` indentation is fine as far as I can see, but a `defrecord` that contains protocol implementations indents functions incorrectly as described above, for example:

```
  (start [component]
         (info "Starting judge - loading rules")
         (assoc component :oden-rules (delay (rules/create-oden-rules db))))
```

**Comment by j0ni** [comment]
Ignore my last comment - I removed old config which used the old backtracking indentation configuration, and it started working correctly again.

Sorry for the noise.

**Comment by niwinz** [comment]
I confirm that defrecord indentation already works correctly, but letfn has some cases where no indents well. I try to explain me:

```clojure
(letfn [(funcname []
                  dd ;; press [tab] key
```
In this case it indents it wrongly. But if y close the parenthesis, it works as expeced:

```clojure
 (letfn [(funcname []
            dd) ;; press [tab] key
```

In any case, at this moment this issue seems minor because the indentation is now usable. (I was using the old version until now...)

Thank you for the efforts that you are doing in this package \o/

**Comment by niwinz** [comment]
I also can confirm that with extend-protocol methods happens the same thing that with letfn (explained in my last comment.

**Comment by Malabarba** [comment]
Should be done. Let me know if it works.

**Comment by niwinz** [comment]
Yes, it works perfectly. Thank you!

**Comment by muhuk** [comment]
I am still getting protocol methods indented like function calls. 

> I removed old config which used the old backtracking indentation configuration

@j0ni could you share which config you have removed? Is it in `user.behaviors`?

-----

BTW I see 3 `user.behaviors` files:

```
./.config/LightTable/User/user.behaviors
./.config/LightTable/settings/user.behaviors
./lib/lighttable-0.8.0-alpha-linux/resources/app/core/User/user.behaviors
```

It seems LT is using the 1st one. Can I safely delete this `settings` directory?
