### ISSUE TITLE
indentation of conditional forms misbehaves before text is entered

### ISSUE THREAD

**Issue by j0ni** [clojure-emacs/clojure-mode#327]
This seems like a low priority issue.

I'm using `clojure-mode` from melpa, so whatever is current `HEAD` of `master`.

When I start typing a conditional expression and hit the first newline, emacs indents the next line wrongly, like this:

```clojure
(if (pred?)
    ))
```

Reformatting confirms that emacs is doing this intentionally. As soon as I add text, I can reformat and emacs will do the right thing:

```clojure
(if (pred?)
  ()))
```

This also seems to happen for `when` and `if-let`, but then I stopped looking.

I'd rather it did the right thing when I hit return, but it's obviously a minor annoyance and doesn't block anything.

Edit: there seem to be quite a few indentation regressions. Here's another:

```clojure
(defn- test-nil-backend [f]
  (is (thrown-with-msg? ExceptionInfo
                      #"Storage must be initialized before use"
                      (f))))
```

I'll stop now - let me know if more are useful. I'll also explore the possibility that my config has slipped into brokenness by not tracking some important change.

**Comment by magnars** [comment]
I'm seeing the bug too. This feels jarring, and I have to constantly tab to fix the indentation while typing.

**Comment by Malabarba** [comment]
Thanks. It's a certainly a regression due to us depending a little less on lisp-mode for indentation (which was necessary to fix other bugs). I'll look into it when I get a chance.

**Comment by magnars** [comment]
Thanks for the fix :)
