### ISSUE TITLE
clojure-mode causing Emacs to hang while using evil-mode

### ISSUE THREAD

**Issue by MichaelVessia** [clojure-emacs/clojure-mode#330]
I am running Emacs 24 with evil-mode, and when I have a .clj buffer open and go to the end of the buffer and press o to create a new line and enter insert mode, emacs hangs. I can see that I am in insert mode, but I'm unable to type. If i press ctrl-g I am left in insert mode, the new line is created, and all works well.  

This does not happen on any other line except the last line of the buffer.  It only happens when i use o on the last line of the buffer, and only occurs in .clj buffers.

I am new to both clojure and emacs so please let me know if any other information would help.  I have isolated this to clojure-mode, having had the issue go away if i disable it.

**Comment by expez** [comment]
Can't reproduce.  

Try updating with the latest version of everything from MELPA and see if the problem persist.

If it does, do `M-x toggle-debug-on-quit <RET>`, reproduce the problem, hit <kbd>C-g</kbd> when emacs hangs, and paste the resulting backtrace here.

**Comment by MichaelVessia** [comment]
The problem is still present.  Updated all my installed packages.  Here is my output.  Excuse what i believe is a color code output mess not sure how to get rid of that.

Debugger entered--Lisp error: (quit)
  clojure-forward-logical-sexp(1)
  #[0 "`\300X\205\302\303!\210\301\211\242T\240\210\202\207" [3760 (324134) clojure-forward-logical-sexp 1] 2 "\n\n(fn)"]()
  funcall(#[0 "`\300X\205\302\303!\210\301\211\242T\240\210\202\207" [3760 (324134) clojure-forward-logical-sexp 1] 2 "\n\n(fn)"])
  #[771 "\302C\303\304\305\306\307\310\311\n\"\312\"\313\314%D\315\304\305\316\317\310\311	!\320\"\321\322%\303EDC\217\210\211\242TU\2037\\\202J\211\242TV\203E\323	!\202J\313_\\\207" [lisp-body-indent calculate-lisp-indent-last-sexp -1 err funcall make-byte-code 0 "`\300X\205\302\303!\210\301\211\242T\240\210\202\207" vconcat vector [clojure-forward-logical-sexp 1] 2 "\n\n(fn)" scan-error 257 "\300\211\242T\240\207" [] 3 "\n\n(fn IGNORED)" clojure--normal-indent] 14 "\n\n(fn INDENT-POINT METHOD CONTAINING-FORM-COLUMN)"](3760 1 2)
  clojure-indent-function(3760 (2 3710 3753 nil nil nil 0 nil nil (3468 3710)))
  calculate-lisp-indent()
  lisp-indent-line()
  clojure-indent-line()
  indent-according-to-mode()
  evil-open-below(1)
  call-interactively(evil-open-below nil nil)
  command-execute(evil-open-below)

**Comment by expez** [comment]
Did you restart emacs after updating all your packages?  If not, the update didn't take effect.  If this is the bug I think it is, then it was fixed last week.

**Comment by MichaelVessia** [comment]
I upgraded all of my packages, and restarted emacs.  Emacs is up to date as well.

**Comment by expez** [comment]
Aright, final two questions:

1.  If you go into the `elpa` dir in `~/.emacs.d` do you see a single clojure-mode dir, called `clojure-mode-20151001.2255`?
2. Is you `.emacs` on github up to date?  I might have to clone that to reproduce the issue. If 1) doesn't help us out (by just deleting the other clojure-mode dir causing old code to load).

**Comment by MichaelVessia** [comment]
1)
ls ~/.emacs.d/elpa | grep clojure
clojure-mode-20151001.2255

2)
https://github.com/MichaelVessia/dotfiles/blob/master/.emacs

Here is my up to date .emacs

**Comment by MichaelVessia** [comment]
The same thing can be produced by simply entering insert mode and pressing enter in an attempt to create new lines.  If done with the cursor on the last line of the file, it will cause emacs to hang.

**Comment by MichaelVessia** [comment]
I unintentionally rid myself of this bug while changing some things around in my .emacs.  I suspect it was   a conflicting package.  Thank you for the help.
