### ISSUE TITLE
reify indentation

### ISSUE THREAD

**Issue by ernestas** [clojure-emacs/clojure-mode#335]
Emacs: 24.5.1
OS: Arch Linux
clojure-mode: 4.2.0-snapshot

I am getting this indentation with reify:

```clojure
(reify
    om/IRender
  (render [this]))
```

Should it not be:

```clojure
(reify
  om/IRender
  (render [this]))
```

**Comment by bbatsov** [comment]
It's supposed to be:

```
(reify om/IRender
  (render [this]))
```

I don't think anyone ever considered an alternative form of indentation for this in `clojure-mode`. That's a general issue with most macros that have a few arguments plus a body.

**Comment by alvinfrancis** [comment]
I'm getting this as well with multiple protocols:

    (reify
        protocol1 (test-fn1 [_])
        protocol2 (test-fn2 [_])
        protocol3 (test-fn3 [_]))

Is this also expected? Or should the first protocol always be in the same line as `reify`?

It used to be that it indented it like this:

    (reify
      protocol1 (test-fn1 [_])
      protocol2 (test-fn2 [_])
      protocol3 (test-fn3 [_]))

**Comment by bbatsov** [comment]
I'm guessing that before we start thinking about a solution we should identify all possible use-cases of `reify` and the desired indentations for them.

**Comment by ernestas** [comment]
I think there are two:

```clojure
(reify Protocol1
  (fn1 []))

;; and

(reify
  Protocol1
  (fn1 [])
  (fn2 [])
  Protocol2
  (fn3 []))
```

This is how it is indented in 4.1.0.

I would like to help with this one, but not sure if I am running the tests correctly in #336.

**Comment by Malabarba** [comment]
I think the most reasonable solution here is to change the reify indent spec to `:defn`.
This should satisfy all of the examples above.

**Comment by bbatsov** [comment]
Yeah, the two examples provided above are definitely the most common in the wild. I'm guessing we might have similar issues with other macros with the same structure.

**Comment by featalion** [comment]
I have the same issue. `:defn` does not work well, too, because inner functions indentation is broken then:

```clojure
(reify
 om/IRender
 (render [this]
         (let [indent-test :fail]
           ...)))
```

**Comment by Malabarba** [comment]
@featalion Thanks for trying it out.
I think this should cover all cases then:

    (put-clojure-indent 'reify '(:defn (1)))

**Comment by alvinfrancis** [comment]
@Malabarba Not familiar with the new indentation specs, but that works perfectly for me. Thanks for sharing.

**Comment by bbatsov** [comment]
> @Malabarba Not familiar with the new indentation specs

That's why we have https://github.com/clojure-emacs/clojure-mode/issues/329 :-)

**Comment by Malabarba** [comment]
Ok, just pushed the reify spec.
Please do mention if there are other macros that need to be updated

**Comment by Malabarba** [comment]
And the new indent spec is now explained in the readme.
