### ISSUE TITLE
Unable to make indentation tests fail

### ISSUE THREAD

**Issue by ernestas** [clojure-emacs/clojure-mode#336]
Emacs: 24.5.1
OS: Arch Linux
clojure-mode: 4.2.0-snapshot

The indentation tests defined with `def-full-indent-test` do not seem to work.

Running this command to test: `cask exec ert-runner`.

**Comment by bbatsov** [comment]
What do you mean by "do not seem to work"? A repro example would be useful.

**Comment by ernestas** [comment]
Sorry for the vagueness.

1. Change the strings defined in any of the `def-full-indent-test` to a different indentation.
2. Tests will still pass.

**Comment by Malabarba** [comment]
God, that was stupid of me. Thanks for noticing. :+1:
