### ISSUE TITLE
Question: indenting cond

### ISSUE THREAD

**Issue by schmir** [clojure-emacs/clojure-mode#337]
I've previously used

    (put 'cond 'clojure-backtracking-indent '(2 4 2 4 2 4 2 4 2 4 2 4 2 4 2 4 2 4 2 4 2 4 2 4 2 4 2 4 2 4))
    (put-clojure-indent 'cond nil)

in my emacs .init.el, which gave me indentation like

    (cond
      foo?
	:foo
      bar?
	:baz)

for cond expressions.

The indent logic has been rewritten in
99629deca7938e5a3f359ea3c3896c4a6ca3f5ef and now I can't get clojure
mode to indent the above in the same way.

Is it still possible to indent like I previously did and if it this,
can you show me the code how to do that?

Thanks

**Comment by Malabarba** [comment]
Technically yes.
The new indent logic is roughly based on the assumption that each form will have a few "special" arguments (indented by 4 spaces) which are then followed by regular arguments (indented by 2 spaces). You can't go back and forth between special and regular.

However, you can set the indent spec to a function, which should allow you to do pretty much anything.

**Comment by Malabarba** [comment]
Here's something that works for me (note that I just fixed a bug related to this a few minutes ago, so you may need to wait for Melpa to update)


    (defun indent-cond (indent-point state)
      (goto-char (elt state 1))
      (let ((pos -1)
            (base-col (current-column)))
        (forward-char 1)
        ;; `forward-sexp' will error if indent-point is after
        ;; the last sexp in the current sexp.
        (ignore-errors
          (while (<= (point) indent-point)
            (clojure-forward-logical-sexp 1)
            (cl-incf pos)))
        (+ base-col (if (evenp pos) 0 2))))
    (put-clojure-indent 'cond #'indent-cond)

**Comment by schmir** [comment]
Thank you very much. The above code works perfectly. I'm using this
with the numbers 4 and 2, which indents like

```clojure
(cond
  foo?
    :foo
  bar?
    :bar)
```
(the indentation in my original example wasn't quite what I wanted,
since I used tab characters, which github failed to render correctly)

For those just copying and pasting, here's the complete version:

```elisp
(defun indent-cond (indent-point state)
  (goto-char (elt state 1))
  (let ((pos -1)
        (base-col (current-column)))
    (forward-char 1)
    ;; `forward-sexp' will error if indent-point is after
    ;; the last sexp in the current sexp.
    (condition-case nil
        (while (and (<= (point) indent-point)
                    (not (eobp)))
          (clojure-forward-logical-sexp 1)
          (cl-incf pos))
      ;; If indent-point is _after_ the last sexp in the
      ;; current sexp, we detect that by catching the
      ;; `scan-error'. In that case, we should return the
      ;; indentation as if there were an extra sexp at point.
      (scan-error (cl-incf pos)))
    (+ base-col (if (evenp pos) 4 2))))
(put-clojure-indent 'cond #'indent-cond)
```
