### ISSUE TITLE
Don't fon't lock the `/` in namespaced keywords

### ISSUE THREAD

**Issue by bbatsov** [clojure-emacs/clojure-mode#339]
In something like `:some.ns/keyword`, the `/` shouldn't be font-locked as part of the keyword.

**Comment by Malabarba** [comment]
Actually, now I remember why it's like this. It's the same way we font lock vars.
For instance, in `s/trim`, the `/` is treated as part of the symbol, not the alias.

Do we want to change it for both keywords and symbols?

**Comment by bbatsov** [comment]
> Actually, now I remember why it's like this. It's the same way we font lock vars.

I'm pretty sure that's not true (just checked it - for vars the `/` is not font-locked, otherwise I wouldn't have pointed this out. It's just a separator - it's neither part of the ns, nor the var name.

**Comment by Malabarba** [comment]
Yes, it's not font-locked, just like the rest of the var name. That's why I thought it was treated as part of the var name. :-)

Anyway, I thought this issue was asking to font-lock the `/` as part of the alias, but now I get the impression you just want to not font-lock it at all?

**Comment by bbatsov** [comment]
Yes, it shouldn't be font-locked at all.

**Comment by Malabarba** [comment]
Ok. I think that might look a little weird. But I'm pushing so we can give it a try.

**Comment by expez** [comment]
> Ok. I think that might look a little weird

Looks good to me :)
