### ISSUE TITLE
defprotocol docstring indentation is weird

### ISSUE THREAD

**Issue by jonathanj** [clojure-emacs/clojure-mode#356]
The docstring indentation for defprotocol method docstrings aligns them with the 
parameter list which seems inconsistent with everything else that takes this same form:

```clojure
(defprotocol IFoo
  (foo [this]
       "Why is this over here?"))
```

Is this the intended behaviour? I was expecting something more like this:
```clojure
(defprotocol IFoo
  (foo [this]
    "I was expecting this"))
```

**Comment by bbatsov** [comment]
Yeah, that's a bug for sure. @Malabarba will you, please, look into it?

**Comment by Malabarba** [comment]
Yes. It's on my todo list. ☺👍
