### ISSUE TITLE
Align Let Expressions

### ISSUE THREAD

**Issue by AshtonKem** [clojure-emacs/clojure-mode#357]
Currently clojure-mode indents let expressions as below:

``` clojure
(let [bar 1
      x 5
      very-long-expression 15]
  (flobnicate bar x very-long-expression))
```

It'd be pretty nice if optionally it could adjust for variable length and align like the following:

``` clojure
(let [bar                  1
      x                    5
      very-long-expression 15]
  (flobnicate bar x very-long-expression))

```

I find myself manually adjusting code to improve legibility, and it's kind of frustrating to do continuously.

**Comment by tanzoniteblack** [comment]
Personally, I've always found the aligned let slightly awkward to read and never been a fan of it, but there is an emacs package that someone made to do exactly this https://github.com/gstamp/align-cljlet .

**Comment by bbatsov** [comment]
Actually, we're going to support exactly what @AshtonKem requested. @Malabarba is working on it, see https://github.com/clojure-emacs/clojure-mode/pull/347

**Comment by bbatsov** [comment]
> Personally, I've always found the aligned let slightly awkward to read and never been a fan of it, but there is an emacs package that someone made to do exactly this https://github.com/gstamp/align-cljlet .

I'm not using this style myself, but for those using it https://github.com/clojure-emacs/clojure-mode/pull/347 will be a much nicer option than having to reformat let sections all the time with `align-cljlet`.

**Comment by AshtonKem** [comment]
I think the "optionally" is a very important part of my request, and it's good to know that it's being worked on.

**Comment by AshtonKem** [comment]
It seems this is a duplicate of #347, so I'm gonna close this.
