### ISSUE TITLE
Align a nested map

### ISSUE THREAD

**Issue by rfkm** [clojure-emacs/clojure-mode#360]
Run `clojure-align` against the following code:

```clj
{:a {:a :a
     :bbbb :b}
 :bbbb :b}
```

Then you'll get:

```clj
{:a    {:a :a
     :bbbb :b}
 :bbbb :b}
```

Is this intended behavior?
`align-cljlet` can do this in one step:
```clj
{:a    {:a    :a
        :bbbb :b}
 :bbbb :b}
```

**Comment by bbatsov** [comment]
Yeah, there's room for improvement here. @Malabarba will you, please, look into this?

**Comment by Malabarba** [comment]
Of course!

**Comment by rfkm** [comment]
Sorry, I lied.
`align-cljlet` can not do this in _one_ step.
Actually, it requires two steps:

```clj
{:a {:a :a
     :bbbb :b}
 :bbbb :b}

{:a    {:a :a
        :bbbb :b}
 :bbbb :b}

{:a    {:a    :a
        :bbbb :b}
 :bbbb :b}
```

This behavior is acceptable to me. (Of course, it would be nice if the recursive version is _optionally_ available.)
So, the only problem is `clojure-align` doesn't indent after alignment?

**Comment by Malabarba** [comment]
> So, the only problem is clojure-align doesn't indent after alignment?

Yes, exactly.

**Comment by rfkm** [comment]
@Malabarba 
Great, thanks! I've confirmed the fix works.

However, I've found another problem...

Run `clojure-align` against the following map:

```clj
{:a {:a :a
     :aaaaaaaaaaaaaaaaaaaaaa :a}
 :b {:a :a
     :aa :a}}
```

Then:

```clj
{:a {:a                      :a
     :aaaaaaaaaaaaaaaaaaaaaa :a}
 :b {:a :a  ; <-
     :aa :a}}
```

It works with the following map:

```clj
{:a {:a :a
     :aaaaaaaaaaaa :a}  ; <- decrease the number of `a`
 :b {:a :a
     :aa :a}}
```

Probably, `end` passed to `clojure--find-sexp-to-align` should be a marker?

**Comment by bbatsov** [comment]
> Run clojure-align against the following map:

Btw, it's way more convenient to use `TAB` to align. In my mind this functionality was always intended to be used like this (smarter indentation versus the needed to realign manually with the explicit command).

**Comment by rfkm** [comment]
Yeah, the automatic mode is very convenient, but some people seem not to prefer such a code style, so I hesitate to enable it globally.
Maybe I'll use it for my personal project :)

**Comment by Malabarba** [comment]
>
> Probably, end passed to clojure--find-sexp-to-align should be a marker?
>
Good catch! :-)

**Comment by rfkm** [comment]
@Malabarba Thanks a lot!
