### ISSUE TITLE
Vertical alignment doesn't treat , correctly

### ISSUE THREAD

**Issue by arrdem** [clojure-emacs/clojure-mode#367]
```clojure
(def ^:private start-element
  {:meta "^", :meta* "#^", :vector "[",       :map "{"
   :list "(", :eval "#=",  :uneval "#_",      :fn "#("
   :set "#{", :deref "@",  :reader-macro "#", :unquote "~"
   :var "#'", :quote "'",  :syntax-quote "`", :unquote-splicing "~@"})
```

indents with align-vertically to 

```clojure
(def ^:private start-element
  {:meta "^"  , :meta* "#^" , :vector        "["  ,       :map        "{"
   :list "("  , :eval  "#=" ,  :uneval       "#_" ,      :fn          "#("
   :set  "#{" , :deref "@"  ,  :reader-macro "#"  , :unquote          "~"
   :var  "#'" , :quote "'"  ,  :syntax-quote "`"  , :unquote-splicing "~@"})
```

since `,` is lexical whitespace, the `,`s should remain attached to the preceding forms.

**Comment by Malabarba** [comment]
That happens because `clojure-forward-logical-sexp` doesn't skip over the comma. I wonder whether we should fix that in `forward-sexp`, `clojure-forward-logical-sexp`, or in `clojure-align`.

**Comment by bbatsov** [comment]
Seems to me `forward-sexp` would be the best place to fix this, as everything else builds on top of it.

**Comment by arrdem** [comment]
I'll take a swing at this after I get 8hrs.

**Comment by bbatsov** [comment]
@arrdem I guess you meant to write 8days. :-)

**Comment by arrdem** [comment]
_squints, drags self out of bed_
