### ISSUE TITLE
Remove highlighting current sexp

### ISSUE THREAD

**Issue by mkwatson** [clojure-emacs/clojure-mode#374]
How do I remove highlighting the current innermost sexp?

![image](https://cloud.githubusercontent.com/assets/2040833/14185035/fb09023e-f72c-11e5-8519-c8c24b0c314a.png)

### clojure-mode version information
```
clojure-mode (version 5.2.0)
```
### Emacs version
*24.5*
### Operating system
*OSX 10.11*

**Comment by Malabarba** [comment]
That looks like rainbow-delimiters or some similar package...

**Comment by ernestas** [comment]
Looks like hl-sexp.

**Comment by mkwatson** [comment]
@ernestas Thanks! Somehow I missed hl-sexp. I've been killing modes without success until that.
