### ISSUE TITLE
Font-lock escape characters in strings

### ISSUE THREAD

**Issue by bbatsov** [clojure-emacs/clojure-mode#378]
It'd be nice if we font-locked specially escape characters in strings - e.g. the `\n` in "this\nthat". This would make it easier to spot strings with embedded escape chars.

I've seen this in some major modes, so I'm guessing it shouldn't be very hard to do.

**Comment by Malabarba** [comment]
Are backslashes ever used for anything other than escape characters? If not, this should be easy to do.

**Comment by Malabarba** [comment]
Oh of course, they're also used for character literals. In that sense, I don't know how to font-lock one and not the other.

**Comment by bbatsov** [comment]
> Oh of course, they're also used for character literals. In that sense, I don't know how to font-lock one and not the other.

I think it's ok to use the same font-locking in both scenarios. You can also see how it's done here https://github.com/lunaryorn/puppet-mode/blob/master/puppet-mode.el#L175

**Comment by Malabarba** [comment]
Actually, looks like we already do that for regexp constructs. So it shouldn't be too hard to copy.

**Comment by Malabarba** [comment]
Or do we actually prefer to also font-lock character literals differently?

**Comment by bbatsov** [comment]
I guess using the same technique will do just fine.
