### ISSUE TITLE
Add :never-align option

### ISSUE THREAD

**Issue by arichiardi** [clojure-emacs/clojure-mode#382]
This is more of a feature request than a bug and it is useful because `re-frame` has this very nice trick for debugging but it needs to wrap sexp with `trace-forms`.

## Expected behavior

```
(trace-forms ...

(rf/register-handler :reset-db app-mw
  ...)

...many other handlers...

)
```

## Actual behavior
```
(trace-forms ...

 (rf/register-handler :reset-db app-mw
   ...)

  ...many other handlers...

)
```
### clojure-mode version information

*Include here the version string displayed by `M-x
```
clojure-mode (version 5.3.0)
```

I was playing with clojure-mode and added a `:never-align` option inside this [`cond`](https://github.com/clojure-emacs/clojure-mode/blob/master/clojure-mode.el#L1151) `clojure--normal-indent`. The only thing I think is that I need to add something else so that [`clojure-indent-function`](https://github.com/clojure-emacs/clojure-mode/blob/master/clojure-mode.el#L1255) does not pass `:always-align` by default.

Before keeping working on this I wanted to ask if it is something worth working on :smile:

**Comment by arichiardi** [comment]
Given #384 this now works, I don't know if it makes still sense to have an explicit key for it, I'll leave this decision to you guys, feel free to close this if not.

**Comment by Malabarba** [comment]
I think I'll close this. The indentation engine is complicated enough already. :-)
