### ISSUE TITLE
Custom Vertical Alignment

### ISSUE THREAD

**Issue by freckletonj** [clojure-emacs/clojure-mode#388]
I would love if, for example, we could align `core.match` statements, such as:

```clojure
(match [val branches]
       ['type ['string]] 's/Str
       ['type ['num]]    's/Num
       ['enum x]         (list 'enum x)
 
       ['type [ (['enum x] :seq) ]] (list 's/enum x)
       [v () b]                     {(keyword v) b})
```

instead of:

```clojure
(match [val branches]
      ['type ['string]] 's/Str
      ['type ['num]] 's/Num
      ['enum x] (list 'enum x)

      ['type [ (['enum x] :seq) ]] (list 's/enum x)                 
      [v () b] {(keyword v) b})
```

after pouring over the source code, there doesn't seem to be a way to add this dynamically from my emacs config, `init.el`.

In this case, it would really be as simple as allowing `(match ...)` to work the same as `(cond ...)`.

How could we accomplish this?

**Comment by Malabarba** [comment]
Try `(add-to-list 'clojure-align-cond-forms "match")`. ;-)

**Comment by freckletonj** [comment]
ah, I've spent forever trying to figure this out, works perfectly! thanks!
