### ISSUE TITLE
Incorrect indention of multiple airty protocol forms within defrecord & deftype

### ISSUE THREAD

**Issue by bpoweski** [clojure-emacs/clojure-mode#389]
## Expected behavior

`deftype` & `defrecord` exhibit the same indention regression issue referenced in #344.

```clojure
(deftype Banana []
  Fruit
  (subtotal
    ([item]
     (* 158 (:qty item)))
    ([item a]
     (* a (:qty item)))))
```

## Actual behavior

```clojure
(deftype Banana []
  Fruit
  (subtotal
      ([item]
       (* 158 (:qty item)))
    ([item a]
     (* a (:qty item)))))
```

## Steps to reproduce the problem

Use the above form and indent using <kbd>C-c n</kbd>.

### clojure-mode version information

```
clojure-mode (version 5.5.0-snapshot)
```

### Emacs version

GNU Emacs 24.5.1 (x86_64-apple-darwin14.5.0, NS apple-appkit-1348.17)
 of 2015-10-19

### Operating system

OSX 10.11.5

**Comment by bbatsov** [comment]
Fixed by #390.
