### ISSUE TITLE
wrong syntax class for `?` and `!`

### ISSUE THREAD

**Issue by slipset** [clojure-emacs/clojure-mode#392]
## Expected behavior 
When pressing `C-c C-d d` while point is inside `swap!` I expect to be prompted for the docs about `swap!`

## Actual behavior
I get prompted for the docs about `swap`

## Steps to reproduce the problem
Press `C-c C-d d` and be prompted for docs about `swap`

Same goes for symbols ending with `?`

Executing the following elisp fixes the problems, but I don't know how much breakage this will incur.
```
(modify-syntax-entry ?! "w")
(modify-syntax-entry ?? "w")
```
### CIDER version information

```
;; CIDER 0.13.0snapshot (package: 20160524.714), nREPL 0.2.12
;; Clojure 1.8.0, Java 1.8.0_92
```

### Emacs version

 24.5.1

### Operating system

OS X 10.11 "El Capitan"

**Comment by Malabarba** [comment]
I can't reproduce this. `C-c C-d d` prompts me for `swap!`.

**Comment by slipset** [comment]
Strange, what is the class of `!` and `?` in your syntax table for a clojure file?

**Comment by slipset** [comment]
Hmm, when I visit a clj file without cider, things seem to work, that is  `C-M-f` moves me past the `!` in `swap!`. Once I do `M-x cider-jack-in`, `C-M-f` moves me in front of the `!` in `swap!`

**Comment by Malabarba** [comment]
The syntax for `?` and `!` here is `punctuation`. I agree we can change that to `symbol`, but it would be good to figure out why your system breaks and mine doesn't.

**Comment by Malabarba** [comment]
What is `C-M-f` bound to for you on each case?

**Comment by slipset** [comment]
`paredit-forward` in both cases, but I see that the syntax-table describes `!` as `symbol` before `M-x cider-jack-in`, but becomes `punctuation` after...

**Comment by Malabarba** [comment]
Hmm. That's super strange. For me it's punctuation in both cases.

**Comment by slipset** [comment]
Even more strange: After `M-x cider-jack-in`, `C-M-f` works correctly in the `*cider-repl ..*` buffer, but stops working correctly in the `*.clj` buffer.

So, `C-h s` gives before `M-x cider-jack-in` in a `*.clj` buffer:
[syntax-table.txt](https://github.com/clojure-emacs/clojure-mode/files/339966/syntax-table.txt)

After `M-x cider-jack-in` `C-h s` gives in the same `*.clj` buffer:
[syntax-table2.txt](https://github.com/clojure-emacs/clojure-mode/files/339969/syntax-table2.txt)

So it seems as if some syntax is deleted?

Anyways, if I'm the only one who's experiencing this, just close the issue :)

**Comment by slipset** [comment]
Ok, after some debugging of my config, I found the culprit:
https://github.com/jcatw/purty-mode/blob/master/purty-mode.el

**Comment by Malabarba** [comment]
Ah, glad it's solved.
