### ISSUE TITLE
Imenu matching is hardcoded

### ISSUE THREAD

**Issue by vspinu** [clojure-emacs/clojure-mode#393]
As far as I can tell [this](https://github.com/clojure-emacs/clojure-mode/blob/master/clojure-mode.el#L347-L349) usage is not the right way to go about it. 

As a result I cannot add my patterns to `imenu-generic-expression`.  

The line should probably be 

```elisp
(add-to-list 'imenu-generic-expression '(nil clojure-match-next-def 0))
```

**Comment by bbatsov** [comment]
Probably you're right. PR welcome.
