### ISSUE TITLE
Keyword syntax highlighting for Hiccup use cases

### ISSUE THREAD

**Issue by pandeiro** [clojure-emacs/clojure-mode#399]
## Expected behavior

A typical Hiccup vector representing an element can use CSS syntax for defining element ID, as in the div below:

```clojure
[:div#root
 [:p "Hello"]]
```
## Actual behavior

Now clojure-mode only syntax-highlights the portion of the keyword before the `#` character. (Note that `:div.some-class` will be entirely highlighted as expected.)

## Steps to reproduce the problem

Type the `:div#root` vector above in a clojure-mode buffer.

### clojure-mode version information

`clojure-mode (version 5.5.1)`

### Emacs version

GNU Emacs 24.5.1 (x86_64-unknown-linux-gnu, GTK+ Version 3.20.6)

### Operating system

Arch Linux

**Comment by Malabarba** [comment]
Probably due to our recent change to the `#` syntax class. Guess now we have a reason for the previous definition.

**Comment by vspinu** [comment]
This has something to do with `#` in particular. Other characters with the same syntax class `~^@` don't have this problem.

**Comment by vspinu** [comment]
As far as clojure reader is concerned the matters are a bit unclear.  Other prefix characters except `#` are not allowed by the clojure reader. There is a relevant open clojure issue [here](http://dev.clojure.org/jira/browse/CLJ-889?focusedCommentId=43429#comment-43429) (please upvote).  

The original problem is easy to fix, but I am puzzled why  `:aaa~bbb` and `:aaa@bbb` are currently highlighted as keywords. The [relevant font-lock regexp](https://github.com/clojure-emacs/clojure-mode/blob/master/clojure-mode.el#L668) doesn't allow for `~` and `@` as those are not symbols. Any ideas?

**Comment by vspinu** [comment]
> The relevant font-lock regexp doesn't allow for ~ and @ as those are not symbols. Any ideas?

Ok, I figured it out. Font lock syntax table is [overwritten](https://github.com/clojure-emacs/clojure-mode/blob/master/clojure-mode.el#L753) and `#` is not part of it.
