### ISSUE TITLE
Could we have the On-the-fly evaluation/substitution mode?

### ISSUE THREAD

**Issue by liuchong** [clojure-emacs/clojure-mode#403]
https://github.com/Fuco1/litable
the above link is a "On-the-fly evaluation/substitution of emacs lisp code", which inspired by Light Table's similar feature.
seems nice, would we have this? :joy_cat:

**Comment by Malabarba** [comment]
We have `cider-enlighten-mode`. It's still a little experimental, but you can try turning it on. ;-)

**Comment by liuchong** [comment]
@Malabarba 谢谢 :new_moon_with_face:

**Comment by liuchong** [comment]
but is there any document about the usage? :joy_cat:

**Comment by Malabarba** [comment]
;-) https://cider.readthedocs.io/en/latest/miscellaneous_features/#enlighten-display-local-values

**Comment by liuchong** [comment]
thanks!
