### ISSUE TITLE
Use customizable prefix key

### ISSUE THREAD

**Issue by xiongtx** [clojure-emacs/clojure-mode#407]
## Expected behavior

The prefix key for `clojure-mode-map` should be customizable, as it is in packages like [Projectile](https://github.com/bbatsov/projectile/blob/master/projectile.el#L202).

## Actual behavior

The `C-c C-r` key sequence is [hard-coded](https://github.com/clojure-emacs/clojure-mode/blob/master/clojure-mode.el#L194).

## Steps to reproduce the problem

Obvious.

## Environment & Version information

Not needed.

### clojure-mode version information

`clojure-mode`: 5.5.2

### Emacs version

Emacs: 24.5.50.1

### Operating system

OS: Fedora 14

**Comment by bbatsov** [comment]
> The prefix key for clojure-mode-map should be customizable, as it is in packages like Projectile.

I'm guessing you only want this to be make customizable. While we can certainly do this, it will always fall under `C-c ...`, so I don't think there would be much benefit from something like this.

**Comment by vspinu** [comment]
This should be done with a prefix map. `clojure-mode-refactor-map` seems like an appropriate name.

**Comment by bbatsov** [comment]
I mentioned this in the matching PR #408.

**Comment by xiongtx** [comment]
I didn't know about the `C-c ...` [convention for major modes](https://www.gnu.org/software/emacs/manual/html_node/elisp/Major-Mode-Conventions.html#Major-Mode-Conventions). But if it's customizable, the user can just set it to whatever they want, not necessarily `C-c`.

In any case, I'll opt to close this pull request, since the added value seems to be very small (or non-existent).
