### ISSUE TITLE
`clojure-sort-ns` should do more

### ISSUE THREAD

**Issue by xiongtx** [clojure-emacs/clojure-mode#409]
## Expected behavior

While the `ns` macro is quite complex and gives users leeway in what they can do, there are [good practices](https://stuartsierra.com/2016/clojure-how-to-ns.html) to follow.

`clojure-sort-ns` should implement at least some of these, such as putting `:refer-clojure` before `:require`, which in turn should be before `:import`.
## Actual behavior

`clojure-sort-ns` only sorts the forms after `:require`, `:import`, etc.

The following is considered "sorted"; more can be done.

``` clojure
(ns foo.core
  (:gen-class)
  (:import
   (org.apache.bar Epsilon Delta)
   (java.baz Charlie Beta Alpha))
  (:require [quuz.core :as quuz]))
```
## Environment & Version information

Not necessary.
### clojure-mode version information

`clojure-mode`: 5.5.2
### Emacs version

Emacs: 24.5.50.1
### Operating system

OS: Fedora 24

**Comment by Malabarba** [comment]
While I agree with Stuart's recomendations, I'm unsure if we want enforce them on this command. The way it is right now (IIRC), `clojure-sort-ns` will preserve whatever practice you decided to use, and I think that makes for a more useful command in general.
For instance, I know for a fact a lot of people would stop using the command if it enforced line breaks after the `:keywords`.

A defcustom for this would be acceptable, though.

**Comment by xiongtx** [comment]
Style issues are always controversial, but there are some things that make total sense, like [sorting imported class names lexicographically](https://stuartsierra.com/2016/clojure-how-to-ns.html#sorting), which `clojure-sort-ns` does not do.
