### ISSUE TITLE
Add an arity to a function

### ISSUE THREAD

**Issue by benedekfazekas** [clojure-emacs/clojure-mode#410]
By default I define functions as

```
(defn func [arg]
  body)
```

Adding an arity to such a function requires
1. Wrapping the existing arglist and body in parens,
2. Inserting a set of parens, and
3. Defining a new arglist.

This is the most tedious refactoring I regularly do, and seems like a good candidate for a clj-refactor operation. I don't have any suggestions for how such an operation ought to work; any automated system ought to beat doing it manually.

Originally crated by @exupero on clj-refactor.el: clojure-emacs/clj-refactor.el#349

**Comment by benedekfazekas** [comment]
@bbatsov perhaps creating `enhancement` and `refactor` labels may make sense for this and future issues?

**Comment by bbatsov** [comment]
Done.
