### ISSUE TITLE
clojure-mode-version was not updated for release of 5.6.0

### ISSUE THREAD

**Issue by rwhogg** [clojure-emacs/clojure-mode#416]
## Expected behavior

The variable `clojure-mode-version` should match the release number.

## Actual behavior

The variable `clojure-mode-version` remains at 5.5.2 instead of 5.6.0.

## Steps to reproduce the problem

This can be observed by inspection. See https://github.com/clojure-emacs/clojure-mode/blob/master/clojure-mode.el#L82

### clojure-mode version information

```
clojure-mode (version 5.5.2)
```

Note that this is using the latest code from master.

### Emacs version

Aquamacs 3.3 (based on GNU Emacs 25.1.1)

### Operating system

macOS El Capitan

**Comment by dunn** [comment]
https://github.com/clojure-emacs/clojure-mode/pull/417
