### ISSUE TITLE
clojure-align will break #()

### ISSUE THREAD

**Issue by DogLooksGood** [clojure-emacs/clojure-mode#418]
When using clojure-align with `C-c SPC`,  `#( ... )` will be broken.

for example:

```
(let [abcde 1
      x #(inc %)])
```

align this sexp with `C-c SPC`, will cause:

```
(let [abcde 1
      x     # (inc %)])     <-- a whitespace between # and (
```

what we expected is:

```
(let [abcde 1
      x     #(inc %)])
```

### Clojure Mode Version

```
clojure-mode (version 5.7.0-snapshot)
```

### Emacs Version
GNU Emacs 25.1.50.1 (x86_64-apple-darwin15.4.0, NS appkit-1404.46 Version 10.11.4 (Build 15E65))

### Operating System
OS X

**Comment by bbatsov** [comment]
@Malabarba can you take a look into this?

**Comment by dotemacs** [comment]
Just tried to reproduce this with:

- `clojure-mode` 5.7.0-snapshot (specifically `clojure-mode-20170608.2315`) and this bug is not present there either

However, it was with Emacs 25.2.1, but I don't think that it should matter much.

**Comment by vspinu** [comment]
Smartparens hasn't  been working correctly with # since not so long ago. Might be related.

**Comment by dotemacs** [comment]
Not sure how smartparens would be related to `clojure-align` defined in `clojure-mode`, but just for completeness sake: disabled smartparens-mode and the error is not reproducible.

@DogLooksGood is this error still present for you?

**Comment by j-cr** [comment]
Can't reproduce too. Also, this is an old issue; I think closing it will do no harm?

**Comment by bbatsov** [comment]
👍

**Comment by DogLooksGood** [comment]
Can't reproduce now with latest version.
