### ISSUE TITLE
Make clojure-cycle-if handle if-let

### ISSUE THREAD

**Issue by expez** [clojure-emacs/clojure-mode#421]
Currently it only handles `if` and `if-not`.  Extending it to also handle `if-let` should be trivial.

**Comment by bbatsov** [comment]
`if-let` has different semantics, so I don't think it makes sense to add it to the cycling here.

**Comment by expez** [comment]
Yeah, I forgot how this worked, I thought it just swapped the `if-then` branches, but it does more.
