### ISSUE TITLE
Embedded clojure-built-in-vars does not highlighted correctly

### ISSUE THREAD

**Issue by jasondf** [clojure-emacs/clojure-mode#428]
My environment is :
clojure-mode version: 5.7.0
Emacs version: 25.1.1
OS: Mac OS X 10.11.6

When I type expressions in a clojure file, eg. core.clj, like followings:

`(clojure.string/upper-case "hello world")`
`(clojure.string/upper-case (clojure.string/lower-case "hello world"))`

In the second expression, only the latter clojure-built-in-vars is highlighted(lower-case), the first one(upper-case) doesn't:

<img width="563" alt="screen shot 2017-03-27 at 18 30 57" src="https://cloud.githubusercontent.com/assets/9963736/24352302/9d099f02-131b-11e7-9262-d05984b441a3.png">

**Comment by bbatsov** [comment]
Hmm, `clojure-mode` doesn't highlight those at all. Is this extra highlighting coming from CIDER or the `clojure-mode-extra-font-locking` package?

**Comment by jasondf** [comment]
Oh, my mistake, this came from CIDER, sorry.

**Comment by bbatsov** [comment]
OK, please file this as a CIDER ticket.
