### ISSUE TITLE
(def s "a string") font locks "a string" as a docstring

### ISSUE THREAD

**Issue by oskarkv** [clojure-emacs/clojure-mode#445]
## Expected behavior

Font lock the string `"a string"` as a string in `(def s "a string")`.

## Actual behavior

The string `"a string"` is font locked as a docstring in `(def s "a string")`.

## clojure-mode version information
```
clojure-mode (version 5.7.0-snapshot)
```

## Proposed solution

I played around with this, and it can be solved by adding a check in this `and` https://github.com/clojure-emacs/clojure-mode/blob/master/clojure-mode.el#L898 in the function `clojure-font-lock-syntactic-face-function`. For example
```
(and ...
  (or (save-excursion
        (goto-char startpos)
        (not (= ?\) (char-after (+ startpos (length (sexp-at-point)) 2)))))
      (string= "defprotocol" firstsym)))
```

This, of course, checks for a closing paren after the string, and if so, it is not considered a docstring, except for `defprotocol`, which is the only kind of form that can have a docstring in the last position. Instead of checking for a paren, one could of course check for another element, but it is more involved.

Opinions, suggestions, etc?

**Comment by Macroz** [comment]
Your proposed fix works for me.

**Comment by vspinu** [comment]
Relatedly in

```clj
(s/def :some/keyword (some-spec))
```
`:some/keyword` is highlighted with `font-lock-function-name-face` instead of the keyword-face.

**Comment by bbatsov** [comment]
@vspinu That one should be easier to fix. Just a minor regexp tweak.

**Comment by bbatsov** [comment]
@oskarkv File a PR and we can discuss the potential fix there. I'm a bit concerned about potential performance implications on larger buffers, but overall the approach seems reasonable, although it seems to be it won't work for `ns` for instance, so maybe it should be scope to just `def` or something like this.

**Comment by bbatsov** [comment]
e.g. `(ns some.ns "some docstring")`.

**Comment by Macroz** [comment]
Hmm this works for me in `ns` case also but it might be because I'm running a slightly customized version of `clojure-mode` with more specific faces for `ns` and `defn` as you can see from the screenshot.
![works-for-me](https://user-images.githubusercontent.com/823661/32227421-0a3f6cb2-be54-11e7-8ab7-887dcd6f927f.png)

**Comment by Macroz** [comment]
`ns` works if there are requires etc, not without them.

**Comment by bbatsov** [comment]
That's what I meant. :-)

**Comment by bbatsov** [comment]
Perhaps this should just check for a list of specific forms (with semantics similar to `def`) and that would be both safe and solves the problem.
