### ISSUE TITLE
ClojureScript font locking issue

### ISSUE THREAD

**Issue by manuel-uberti** [clojure-emacs/clojure-mode#450]
## Expected behavior
Keywords correctly colored. Camel-case symbols completely colored.

## Actual behavior
As reported [here](https://github.com/purcell/color-theme-sanityinc-tomorrow/issues/99):

![screen](https://user-images.githubusercontent.com/8199224/31145152-3a639558-a883-11e7-8df8-4df8ffc98b68.png)

## Steps to reproduce the problem

- install [color-theme-sanityinc-tomorrow](https://github.com/purcell/color-theme-sanityinc-tomorrow) and activate `sanityinc-tomorrow-night`
- create a new ClojureScript file with this content:
```
(defn node-color
  [idx]
  (nth (js->clj d3.schemeCategory20c) idx))
```

### clojure-mode version information
```
clojure-mode (version 5.7.0-snapshot)
```

### Emacs version
GNU Emacs 27.0.50 (build 1, x86_64-debian-linux-gnu, GTK+ Version 3.18.9) of 2017-10-01

### Operating system
Ubuntu 16.04.3

**Comment by manuel-uberti** [comment]
The same thing seems to be happening using [solarized-emacs](https://github.com/bbatsov/solarized-emacs) too.

**Comment by vspinu** [comment]
Now you have a good reason to stick with `(. d3 -schemeCategory20c)` ;)

**Comment by manuel-uberti** [comment]
Oh, well, yes of course :-)

**Comment by manuel-uberti** [comment]
Although this

![screen1](https://user-images.githubusercontent.com/8199224/31171947-f16a9f16-a901-11e7-85f7-f2ad570868ff.png)

doesn't get coloured as `.-value` here:

![screen2](https://user-images.githubusercontent.com/8199224/31171956-fe9329ce-a901-11e7-90ac-285c8662353b.png)

**Comment by bbatsov** [comment]
Likely, the `.`'s the issue. I didn't even know something like this is valid Clojure.

**Comment by manuel-uberti** [comment]
Me neither. Probably ClojureScript behaves a little bit different in this specific case, though.

**Comment by manuel-uberti** [comment]
Just to clear things out: is it something that should be fixed or we can close this issue and forget about it? :)

**Comment by bbatsov** [comment]
Yeah, it should be fixed and it's just related to tweaking the regular expressions we use to detecting the type of some identifier. (at least the second part of the issue is trivial). 

Regarding the first one - I'm not sure how should something like `d3.schemeCategory20c` be font-locked to begin with. It's also going to be impossible to differentiate `d3.scheme` from some namespace.

**Comment by kommen** [comment]
I think I have a similar or even the same issue here, code from https://github.com/Day8/re-frame/blob/c4e59880ccc1872a7a14618e2f8fa66e4b1622cc/src/re_frame/interop.cljs#L1-L4

<img width="315" alt="screen shot 2017-12-21 at 18 18 08" src="https://user-images.githubusercontent.com/258/34267003-8ff7da5c-e67b-11e7-8b1d-daf66e70e097.png">

**Comment by manuel-uberti** [comment]
I think it's the same problem, yes.

**Comment by manuel-uberti** [comment]
![shot](https://user-images.githubusercontent.com/8199224/37967485-cfa9d0ba-31cb-11e8-93c3-9cd4c9b98997.png)

Since it looks this way with latest `clojure-mode`, I think it's safe to close this one.
