### ISSUE TITLE
Highlight all reader conditional branches in cljc mode

### ISSUE THREAD

**Issue by lynaghk** [clojure-emacs/clojure-mode#456]
First, let me say thanks for maintaining `clojure-mode`.
I've been happily using it for years to write Clojure/ClojureScript in Emacs, so if any of ya'll find me in person please make sure I buy you a coffee or beer.

Is there a way to see all branches of a reader conditional with the normal highlighting, rather than having one branch greyed out?
Right now, if a Clojure REPL is running, all cljs branches in reader conditionals are greyed out.

I tried looking through the clojure-mode.el source, but my emacs-foo is not strong enough to understand how font-locking works or how to customize it.

Thanks!
Kevin

## Expected behavior

All branches of reader conditional are highlighted, even if a Clojure REPL is running.

## Actual behavior

Only `clj` branch is highlighted.
Switching to `clojurescript-mode` doesn't change the highlighting

![screenshot 2017-10-27 17 57 13](https://user-images.githubusercontent.com/147919/32091630-ba7d82d8-bb40-11e7-8ff4-9828b7d66615.png)

## Steps to reproduce the problem

Open a cljc file with a reader conditional, start a Clojure REPL.

### clojure-mode version information
```
clojure-mode (version 5.7.0-snapshot)
```

### Emacs version

GNU Emacs 25.3.1 (x86_64-apple-darwin13.4.0, NS appkit-1265.21 Version 10.9.5 (Build 13F1911))

### Operating system

OS X 10.9.5

**Comment by vspinu** [comment]
This is a feature of cider. If you don't run cljs repl, you don't get cljs branch highlighted. You can set `cider-font-lock-reader-conditionals` to nil to deactivate this feature.

**Comment by lynaghk** [comment]
@vspinu Thanks for the quick explanation, I appreciate it! Confirmed that this resolves my issue.
