### ISSUE TITLE
test.check: defspec indentation

### ISSUE THREAD

**Issue by manuel-uberti** [clojure-emacs/clojure-mode#457]
## Expected behavior
```clj
(defspec first-element-is-min-after-sorting
  100
  (prop/for-all [v (gen/not-empty (gen/vector gen/int))]
    (= (apply min v)
       (first (sort v)))))
```

## Actual behavior
```clj
(defspec first-element-is-min-after-sorting
  100
  (prop/for-all [v (gen/not-empty (gen/vector gen/int))]
                (= (apply min v)
                   (first (sort v)))))
```

## Steps to reproduce the problem
- add test.check dependency to your project: `[org.clojure/test.check "0.9.0"]`
- create a `.clj` file and add these requires to your `ns` declaration:
```
[clojure.test.check.clojure-test :refer [defspec]]
[clojure.test.check.generators :as gen]
[clojure.test.check.properties :as prop]
```
- put this `defspec` in the previously created `.clj` file:
```clj
(defspec first-element-is-min-after-sorting
  100
  (prop/for-all [v (gen/not-empty (gen/vector gen/int))]
    (= (apply min v)
       (first (sort v)))))
```
- place cursor right before `(defspec`
- <kbd>M-x indent-sexp</kbd>

### clojure-mode version information
```
clojure-mode (version 5.7.0-snapshot)
```

### Emacs version

GNU Emacs 27.0.50 (build 1, x86_64-debian-linux-gnu, GTK+ Version 3.18.9) of 2017-10-27

### Operating system

Ubuntu 16.04.3

**Comment by vspinu** [comment]
This has little to do with defspec, it's how clojure-mode indents all functions. 

```clj
(prop/for-all [v (gen/not-empty (gen/vector gen/int))]
              (= (apply min v)
                 (first (sort v))
```
If you have control of `prop/for-all` you can place `{:style/indent 1}` in its attributed map and CIDER will pick that up. Alternatively you can fix it on the emacs side with 

```el
(define-clojure-indent
  (for-all 1))
```

**Comment by manuel-uberti** [comment]
Thank you, I'll go for the second option.
