### ISSUE TITLE
Threading refactorings: allow opt-in for same-line results

### ISSUE THREAD

**Issue by vemv** [clojure-emacs/clojure-mode#463]
Hi there!

It'd be nice if `clojure-thread-first-all` and such allowed one to choose what result is desired:

* One newline per threaded expr; pr
* The whole form in a single line.

i.e., sometimes I want `(-> foo bar baz)` rather than:

```
(-> foo
    bar
    baz)
```

My understanding is that there's currently no opt-in?

Cheers - Victor

**Comment by vemv** [comment]
I don't need this feature anymore since I compensated it with this https://github.com/vemv/.emacs.d/blob/9afe61e3987900c422c9c6d2b5748b27a794e007/lib/non-submodules/vemv.lang.el#L1087

**Comment by bbatsov** [comment]
Probably this could have easily been address with a prefix argument, but I' happy you solved your problem.
