### ISSUE TITLE
Clojure-mode-map does not inherit from prog-mode-map

### ISSUE THREAD

**Issue by arichiardi** [clojure-emacs/clojure-mode#467]
## Expected behavior
I expect to see the keybindings defined in my `prog-mode-map` when I use `clojure-mode`.

## Actual behavior
It does not happen.

## Steps to reproduce the problem
Evaluate `(define-key prog-mode-map (kbd "C-c x g") 'git-gutter-mode)` somewhere in your emacs and then enable `clojure-mode`. You won't be able to use `C-c x g`.

### clojure-mode version information
All versions.

I think this should be done for coherence. They actually [did the same](https://debbugs.gnu.org/cgi/bugreport.cgi?bug=14504) for `lisp-mode`.

**Comment by bbatsov** [comment]
Yeah, that makes sense. Done.
