### ISSUE TITLE
Unexpected indentation of top-level string-valued def

### ISSUE THREAD

**Issue by codeasone** [clojure-emacs/clojure-mode#469]
Perhaps related to https://github.com/clojure-emacs/clojure-mode/issues/405 

## Expected behavior

```
(def foo "<character-entered>abc")
``` 

## Actual behavior

```
  (def foo "<character-entered>abc")
``` 

Form indented as a docstring unnecessarily. 

## Steps to reproduce the problem

With the following `var` definition: 
```
(def foo "|abc")
``` 
And cursor at `|` 

Entering any character causes unhelpful indentation:

```
  (def foo "Mabc")
``` 

It appears to be because `clojure-mode` determines that the form is a [docstring](https://github.com/clojure-emacs/clojure-mode/blob/5cf0fd9360dc5a9a95464601319062673d213807/clojure-mode.el#L1207)

Unfortunately I don't have the time to debug the treatment of [syntax-ppss](https://www.gnu.org/software/emacs/manual/html_node/elisp/Position-Parse.html), which I suspect is at the root of the issue. 

## Environment & Version information

```
GNU Emacs 26.0.91 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.18.9) of 2018-01-26
clojure-mode (version 5.7.0-snapshot)
Version: 20180202.922
Commit: 5cf0fd9360dc5a9a95464601319062673d213807
```

The issues does not present with current `melpa-stable` release of `clojure-mode`: 

```
Version: 5.6.1
Commit: fdbdfb91e0a5731bf9a739b70c5f217c5d12ae6d
```

**Comment by bbatsov** [comment]
Yeah, that's basically the same bug. I have a good idea where the problematic code is, but I don't have time to debug it myself either. Adding a real docstring should work as a workaround I guess. 

It's basically a combination of

https://github.com/clojure-emacs/clojure-mode/blob/master/clojure-mode.el#L906

and

https://github.com/clojure-emacs/clojure-mode/blob/master/clojure-mode.el#L1035

We mark the docstring positional statically and we probably need to make this more dynamic homehow (e.g. it's number 2 only if the form has 3 arguments).

**Comment by cichli** [comment]
Thanks for the report.
