### ISSUE TITLE
Any reason why '(' isn't default in clojure-omit-space-between-tag-and-delimiters?

### ISSUE THREAD

**Issue by alexander-yakushev** [clojure-emacs/clojure-mode#470]
I discovered this option only now. Before, I used to type `#_()` which paredit turned to `#_ ()`. This was driving me crazy. I'm happy that I can disable it now, but many people won't ever find this parameter. Thoughts?

**Comment by bbatsov** [comment]
Yeah, this should be the default. It's an oversight and a PR to address this would be welcomed!
