### ISSUE TITLE
Blank lines prevent correct vertical alignment

### ISSUE THREAD

**Issue by vemv** [clojure-emacs/clojure-mode#481]
Assuming I have vertical alignment turned on for maps, the following won't get aligned due to the blank line:

```clojure
{:keys [foo bar

        baz]
 :or {quux 1}}
```

Tried with `clojure-mode-20180809.1455`.

Thanks - Victor

**Comment by vemv** [comment]
The following patch appears to work:

![image](https://user-images.githubusercontent.com/1162994/44195313-f24a5b80-a138-11e8-9617-b9b74d149f27.png)

Would it make sense a PR introducing a defcustom for this? Not sure if some other strategy would be preferred.

**Comment by bbatsov** [comment]
Yeah, this should be solved with a defcustom and default should remain what it's today.

**Comment by Malabarba** [comment]
Sounds good. Sorry for not answering your last question.
