### ISSUE TITLE
end-of-defun skips two top level forms

### ISSUE THREAD

**Issue by mnewt** [clojure-emacs/clojure-mode#485]
I think this is a pretty recent regression, maybe the last week or two.

## Expected behavior

`end-of-defun` skips one top level form at a time.

## Steps

"|" is point

```clj
(defn one)
|
(defn two)

(defn three)

```

`M-x end-of-defun`

```clj
(defn one)

(defn two)
|
(defn three)

```

## Actual behavior

`end-of-defun` skips two top level forms.

## Steps to reproduce the problem

"|" is point
```clj
(defn one)
|
(defn two)

(defn three)

```

`M-x end-of-defun`

```clj
(defn one)

(defn two)

(defn three)
|
```

### clojure-mode version information

I pulled the latest from master (e6bd584).

```
clojure-mode (version 5.8.2)
```

### Emacs version

```
M-x emacs-version
GNU Emacs 27.0.50 (build 1, x86_64-apple-darwin17.7.0, NS appkit-1561.60 Version 10.13.6 (Build 17G65))
 of 2018-08-19
```

### Operating system

macOS 10.13.6

```
> uname -a
Darwin host 17.7.0 Darwin Kernel Version 17.7.0: Thu Jun 21 22:53:14 PDT 2018; root:xnu-4570.71.2~1/RELEASE_X86_64 x86_64 i386 MacBookPro14,3 Darwin
```

**Comment by bbatsov** [comment]
It's probably some regression from the changes @dpsutton did recently in https://github.com/clojure-emacs/clojure-mode/pull/484.

**Comment by dpsutton** [comment]
Most likely. I can look at this tomorrow night. Sorry about that. I can imagine it is incredibly frustrating. I am experiencing this as well. I never use `end-of-defun` but `beginning-of-defun` followed by `paredit-forward` so i never noticed it.

**Comment by bbatsov** [comment]
Yeah, I didn't pay much attention to this in the PR, but we need a matching version of `end-of-defun` that's `comment`-aware.

**Comment by dpsutton** [comment]
makes sense. I looked into `end-of-defun` and I thought it just relied on `beginning-of-defun` and the matching paren is why I didn't go into it more.

**Comment by bbatsov** [comment]
Fixed in https://github.com/clojure-emacs/clojure-mode/pull/487
