### ISSUE TITLE
clojure-toplevel-inside-comment-form broke parens insertion before comment block.

### ISSUE THREAD

**Issue by DogLooksGood** [clojure-emacs/clojure-mode#489]
### Actual behavior and reproduce steps

with `clojure-toplevel-inside-comment-form` set, and `paredit` enabled. Insert a pair of parens
```
()

|   ;; <-- cursor here, type `(`

(comment)
```
will become 
```
()



(|)(comment)  ;; <-- cursor jump to here
```

### clojure-mode version information

```
clojure-mode (version 5.8.2)
```

### Emacs version

GNU Emacs 26.1 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.22.30) of 2018-07-05

### Operating system

Linux

**Comment by bbatsov** [comment]
Sounds like a task for @dpsutton. :-)

**Comment by dpsutton** [comment]
This is weird interaction wit paredit mode but i'm investigating.
