### ISSUE TITLE
clojure-mode claims it is version 5.8.2 even in later versions

### ISSUE THREAD

**Issue by aengelberg** [clojure-emacs/clojure-mode#499]
## Expected behavior

```
M-x clojure-mode-display-version [RET]
"clojure-mode (version 5.9.1)"
```

## Actual behavior

```
M-x clojure-mode-display-version [RET]
"clojure-mode (version 5.8.2)"
```

## Steps to reproduce the problem

```
M-x clojure-mode-display-version [RET]
```

### clojure-mode version information

```bash
$ ls ~/.emacs.d/elpa | grep clojure-mode
clojure-mode-5.9.1
```

### Emacs version

25.3.1

### Operating system

Mac OS X 10.11.3 El Capitan

**Comment by bbatsov** [comment]
Seems I forgot to update the fallback version. It's weird it ended up being used, though.

**Comment by bbatsov** [comment]
Ops, my bad - here don't really do any attempt to extract the package version and the version displayed is taken from a constant in the code. I'll update this at some point.
