### ISSUE TITLE
Allow clojure-align-cond-forms to recognize namespace-qualified forms

### ISSUE THREAD

**Issue by leithdennis** [clojure-emacs/clojure-mode#520]
This is useful for adding user defined functions to the list of `clojure-align-cond-forms` and then calling them from within another ns.

## Expected behavior
Proper indentation:
```
(clojure.core/case :foo
  :foo       "foo"
  :bar       "bar"
  :foobarbaz "foobarbaz")
```
## Actual behavior
Actual indentation is: 
```
(clojure.core/case :foo
  :foo "foo"
  :bar "bar"
  :foobarbaz "foobarbaz")
```
## Steps to reproduce the problem
Take the above code block and run `clojure-align`. Notice that it does not align as non-ns-qualified `case` would.

### clojure-mode version information
```
clojure-mode (version 5.8.2)
```

### Emacs version

`25.3.1`

### Operating system

`macOS 10.13.4`

**Comment by Malabarba** [comment]
Should be safe and simple to extend the default value of `clojure-align-cond-forms` to also include the namespace-qualified version of the symbols. Would you like to try it? :)
