### ISSUE TITLE
Not all characters literals are font locked properly

### ISSUE THREAD

**Issue by yuhan0** [clojure-emacs/clojure-mode#547]
## Expected behavior
Character literals such as `\A` should be highlighted with `clojure-character-face`.

The [official guide](https://clojure.org/guides/weird_characters#_character_literal) does not explicitly state what is allowed, but current Clojure readers accept practically any Unicode character such `\λ`, `\字`, even `\ ` (space)

## Actual behavior
Only punctuation, numbers and lowercase characters are correctly highlighted according to the current rules.
https://github.com/clojure-emacs/clojure-mode/blob/147bf84189ef672161b2229ddc5c35713323ad59/clojure-mode.el#L865

## Steps to reproduce the problem
Insert `\A` in a clojure-mode buffer

### clojure-mode version information
```
clojure-mode (version 5.11.0)
```

### Emacs version
26.3
### Operating system
macOS 10.14

**Comment by yuhan0** [comment]
The actual rules could perhaps be expressed in a regexp like 
```elisp
(rx "\\" (or "newline" "space" "tab" "formfeed" "backspace" "return"
             (: "u" (= 4 (char "0-9A-Fa-f")))
             (: "o" (repeat 1 3 (char "0-7")))
             any)
    (or symbol-end space))
;; =>
"\\\\\\(?:newline\\|space\\|tab\\|formfeed\\|backspace\\|return\\|u[0-9A-Fa-f]\\{4\\}\\|o[0-7]\\{1,3\\}\\|.\\)\\(?:\\_>\\|[[:space:]]\\)"
```
or the more lenient `(rx "\\" (+ any) (or symbol-end space))`

**Comment by bbatsov** [comment]
Agreed. Seems I messed up that regex.
