### ISSUE TITLE
Comment behavior

### ISSUE THREAD

**Issue by cassc** [clojure-emacs/clojure-mode#554]
Line comment not working as expected in older versions. 

## Expected behavior
Type `;;` in front of `:x-func`  should comment out `:x-func [#()]` and add a line break after the s-expression

```clojure
{:esc {:view   :program-stat
       :x-func [#()]}}
```
## Actual behavior

Note the s-expression is broken:

```clojure
{:esc {:view   :program-stat
       ;;:x-func [#()]}}
```

### clojure-mode version

5.11.0 and  20191112.1948

**Comment by yuhan0** [comment]
I believe structural editing modes like Paredit or Lispy already have this feature and work across all Lisp-like languages.

**Comment by cassc** [comment]
@yuhan0 Paredit is what I need. Thank you!
