### ISSUE TITLE
Comment highlighting only works when start of comment is on screen

### ISSUE THREAD

**Issue by expez** [clojure-emacs/clojure-mode#575]
## Expected behavior
Comment highlighting is applied even though the beginning of the comment isn't visible.

## Actual behavior
Only comments where e.g. `;;` or `#_` are visible on screen are syntax highlighted correctly.

## Steps to reproduce the problem

Create a function (or a very long `deftest`) that spans more than one visible page on screen.  Jump to the end of the function / test, and when the the start of the comment isn't visible, call </kbd> M-x revert-buffer </kbd> (to force syntax highlighting to happen again).  Notice that the code doesn't have syntax highlighting matching the commented out state.

### clojure-mode version

```
clojure-mode (version 5.12.0)
```

### Emacs version

25.1.1

**Comment by andreyorst** [comment]
I believe that this is how Emacs' font lock system works. I often see the same behavior in Org Mode, when scrolling up from document's end - source code highlighting kicks in only when `#+begin_src` becomes visible.

**Comment by expez** [comment]
I see.  I typically don't have constructs that are this large (or commented out 🙄) so this was the first time I've seen this behavior.  Guess we should just close this if there's nothing that can be done about this...
