### ISSUE TITLE
clojure-find-ns breaks if the ns form is preceded by whitespace

### ISSUE THREAD

**Issue by bbatsov** [clojure-emacs/clojure-mode#593]
See https://github.com/clojure-emacs/cider/issues/3009

## Expected behavior

`clojure-find-ns` should handle properly an `ns` form with preceding whitespace.

## Actual behavior

It returns `nil`. 

## Steps to reproduce the problem

```clojure
  (ns foo.bar)

(defn foo [] :bar)
```

Try evaluating the `defn` form. 

### clojure-mode version

```
clojure-mode (version 5.10.0)
```

### Emacs version

26.3

### Operating system

Ubuntu 20.04

**Comment by jogo3000** [comment]
I tried to fix this issue by altering the regex to allow whitespace before the ns form. However, @yuhan0 quickly pointed out that this approach may cause unexpected behaviour when ns form is inside a comment block for example.

For example
```
(ns the-actual-ns) 

(comment
  (ns not-the-real-one))
```

**Comment by mizlan** [comment]
> I tried to fix this issue by altering the regex to allow whitespace before the ns form. However, @yuhan0 quickly pointed out that this approach may cause unexpected behaviour when ns form is inside a comment block for example.
> 
> For example
> 
> ```
> (ns the-actual-ns) 
> 
> (comment
>   (ns not-the-real-one))
> ```

How relevant is this problem? What if the buffer contained the following:

```
(comment
(ns not-the-real-one))
```

note the lack of whitespace.
