### ISSUE TITLE
Perhaps make `put-clojure-indent` a "safe" function

### ISSUE THREAD

**Issue by rbrw** [clojure-emacs/clojure-mode#597]
It might be very convenient to be able to add `put-clojure-indent` calls for project-specific forms to a `.dir-locals.el` without causing emacs to prompt about risky evaluation.  Assuming I understand how it works, this might just require adding an appropriate `safe-local-eval-function` property to `put-clojure-indent` https://www.gnu.org/software/emacs/manual/html_node/elisp/File-Local-Variables.html

(If I get time, if no one else beats me to it, and if it's considered interesting, then I might see if I can come up with something to propose later.) 

Thanks

**Comment by DerGuteMoritz** [comment]
AFAICT this was done with https://github.com/clojure-emacs/clojure-mode/pull/598?

**Comment by vemv** [comment]
Thank you!
