### ISSUE TITLE
`.lpy` extension support

### ISSUE THREAD

**Issue by ikappaki** [clojure-emacs/clojure-mode#675]
Hi,

I would like to add [Basillisp ](https://github.com/basilisp-lang/basilisp)file extension, `.lpy`, to the list of supported clojure-mode extensions.

This is just to get minimal support, there are some additional, specific to Basilisp, that can be declared for syntax highlighting, but will add them at later time.

PR to follow.

Thanks

**Comment by bbatsov** [comment]
Sure! Seems like a cool project, btw!

**Comment by bbatsov** [comment]
Closed by #676.
